#!/usr/bin/env python3
"""
gen_world_map_fixture.py - emit a C++-includable terrain-grid fixture for the
world-map reachability guard harness.

Reads the committed tests/world_map_terrain_grid.txt (24 rows x 32 cols of
'#'/'F'/'~') and writes tests/world_map_fixtures.h containing the grid as
row strings. The harness (tests/world_map_harness.cpp) includes that header
and runs the REAL src/world_map_geometry.inl against it.

This runs at build/CI time so the fixture always matches the committed grid;
nothing generated is committed.

USAGE
  python gen_world_map_fixture.py <world_map_terrain_grid.txt> <out world_map_fixtures.h>
"""

import sys

ROWS = 24
COLS = 32
VALID = set("#F~")


def load_grid(txt_path):
    rows = []
    with open(txt_path, "r") as f:
        for raw in f:
            line = raw.rstrip("\n").rstrip("\r")
            if line.startswith("//"):
                continue
            if line.strip() == "":
                continue
            rows.append(line)
    if len(rows) != ROWS:
        raise SystemExit(f"FATAL: expected {ROWS} data rows, got {len(rows)} in {txt_path}")
    for i, r in enumerate(rows):
        if len(r) != COLS:
            raise SystemExit(f"FATAL: row {i} is {len(r)} chars, expected {COLS}: '{r}'")
        bad = set(r) - VALID
        if bad:
            raise SystemExit(f"FATAL: row {i} has invalid char(s) {sorted(bad)}: '{r}'")
    return rows


def emit(txt_path, out_path):
    rows = load_grid(txt_path)
    land = sum(r.count("#") for r in rows)
    forest = sum(r.count("F") for r in rows)
    ocean = sum(r.count("~") for r in rows)

    lines = []
    a = lines.append
    a("// world_map_fixtures.h - GENERATED by tests/gen_world_map_fixture.py. Do not edit.")
    a("// Terrain-grid snapshot for the world-map reachability guard harness,")
    a("// from the committed tests/world_map_terrain_grid.txt.")
    a(f"// Totals: {land} land, {forest} forest, {ocean} ocean (of {ROWS * COLS}).")
    a("#pragma once")
    a("")
    a("namespace WorldMapFixtures {")
    a("")
    a(f"static const int kRows = {ROWS};")
    a(f"static const int kCols = {COLS};")
    a("")
    a("// One char per segment: '#' = land, 'F' = forest, '~' = ocean.")
    a("static const char* kTerrainRows[kRows] = {")
    for i, r in enumerate(rows):
        a(f'    "{r}", // row{i:02d}')
    a("};")
    a("")
    a("} // namespace WorldMapFixtures")
    a("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path}: {ROWS}x{COLS} grid ({land} land, {forest} forest, {ocean} ocean)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: gen_world_map_fixture.py <world_map_terrain_grid.txt> <out world_map_fixtures.h>")
        sys.exit(2)
    emit(sys.argv[1], sys.argv[2])
