#!/usr/bin/env python3
"""
gen_chase_fixture.py - emit a C++-includable walkmesh fixture for the chase
guard harness.

Reads the committed Plan & Research Documents/ff8_walkmeshes.json and writes
tests/chase_fixtures.h containing static vertex/triangle arrays (in the real
FieldArchive::WalkmeshVertex/WalkmeshTriangle layout) for the guarded fields.
The harness (tests/chase_harness.cpp) includes that header and runs the REAL
src/field_nav_pathfinding.inl against it.

This runs at build/CI time so the fixture always matches the committed extract;
nothing extra is committed.

USAGE
  python gen_chase_fixture.py <ff8_walkmeshes.json> <out chase_fixtures.h>
"""

import json
import sys

# Fields the harness needs geometry for.
GUARDED_FIELDS = ["domt2_1", "dotown_3", "bggate_6"]


def emit(json_path, out_path):
    with open(json_path, "r") as f:
        data = json.load(f)
    fields = data.get("fields", {})

    lines = []
    a = lines.append
    a("// chase_fixtures.h - GENERATED by tests/gen_chase_fixture.py. Do not edit.")
    a("// Walkmesh geometry for the chase-guard harness, sliced from the")
    a("// committed ff8_walkmeshes.json. Layout matches FieldArchive::Walkmesh*.")
    a("#pragma once")
    a("#include <cstdint>")
    a('#include "../src/field_archive.h"')
    a("")
    a("namespace ChaseFixtures {")
    a("")
    a("struct Fixture {")
    a("    const char* name;")
    a("    const FieldArchive::WalkmeshVertex*   verts;")
    a("    int                                   vcount;")
    a("    const FieldArchive::WalkmeshTriangle* tris;")
    a("    int                                   tcount;")
    a("};")
    a("")

    present = []
    for name in GUARDED_FIELDS:
        if name not in fields:
            a(f"// WARNING: field '{name}' absent from extract; skipped.")
            continue
        m = fields[name]
        sym = name.replace("-", "_")
        verts = m["vertices"]
        tris = m["triangles"]

        a(f"// ---- {name}: {len(verts)} verts, {len(tris)} tris ----")
        a(f"static const FieldArchive::WalkmeshVertex {sym}_v[] = {{")
        for v in verts:
            a(f"    {{ {int(v['x'])}, {int(v['y'])}, {int(v['z'])} }},")
        a("};")
        a(f"static const FieldArchive::WalkmeshTriangle {sym}_t[] = {{")
        for t in tris:
            vi = t["vertex_indices"]
            nb = t["neighbors"]
            cx = t["center_x"]
            cy = t["center_y"]
            a(f"    {{ {{ {vi[0]}, {vi[1]}, {vi[2]} }}, "
              f"{{ {nb[0]}, {nb[1]}, {nb[2]} }}, {cx}f, {cy}f }},")
        a("};")
        a("")
        present.append((name, sym, len(verts), len(tris)))

    a("static const Fixture kFixtures[] = {")
    for name, sym, vc, tc in present:
        a(f'    {{ "{name}", {sym}_v, {vc}, {sym}_t, {tc} }},')
    a("};")
    a(f"static const int kFixtureCount = {len(present)};")
    a("")
    a("}  // namespace ChaseFixtures")
    a("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path}: {len(present)} fixtures ({', '.join(p[0] for p in present)})")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: gen_chase_fixture.py <ff8_walkmeshes.json> <out chase_fixtures.h>")
        sys.exit(2)
    emit(sys.argv[1], sys.argv[2])
