// tests/jsm_order_fixtures.h -- GENERATED by fieldsim/gen_jsm_order_fixtures.py
// Real .jsm group words and .sym contents, straight off the disc. Do not hand-edit.
#pragma once
struct JsmOrderFixture {
    const char*  name;
    int          nD, nL, nB, nO, ngrp;
    const unsigned short* words;     // group words, ngrp of them
    const char* const*    bare;      // SYM bare list, nO+nL+nB of them
    const char* const*    declName;  // SYM method-section name, by GROUP
    const int*            declMeth;  // that name's method count, by GROUP
};
static const unsigned short kW_eccway11[] = {29319,39809,40065,40321,40577,40835,41347,41859,29,3869,7709,11549,15389,19229,23069,26884,27523,28041,30339,30851,31363,31875,32387,32899,33412,34057,35362,42371,42883,43395};
static const char* const kB_eccway11[] = {"Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Woman","Mother","Lifter","Drow","Director","Timer","Shake","Kossori","info","Disp","atkmes","cardgamemaster","map1scroll","map2scroll","map3scroll","Linejump1","light1","light2","light3","lifter","attackmap1","attackmap2","attackmap3"};
static const char* const kN_eccway11[] = {"Linejump1","light1","light2","light3","lifter","attackmap1","attackmap2","attackmap3","Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Woman","Mother","Lifter","Drow","Director","Timer","Shake","Kossori","info","Disp","atkmes","cardgamemaster","map1scroll","map2scroll","map3scroll"};
static const int kM_eccway11[] = {7,1,1,1,1,3,3,3,29,29,29,29,29,29,29,4,3,9,3,3,3,3,3,3,4,9,34,3,3,3};
static const unsigned short kW_escouse1[] = {11911,12935,18949,19717,20485,21251,6,903,1929,3203,3721,5001,6281,7559,8581,9348,9989,10756,11395,13955,14498};
static const char* const kB_escouse1[] = {"Squall","Zell","Selphie","Rinoa","Quistis","Irvine","Edea","Angelo","Worker0","Worker1","Worker2","Worker3","Director","queen_spa","cardgamemaster","ShakeOn","Movie","door","doorlight"};
static const char* const kN_escouse1[] = {"ShakeOn","Movie","Door1","Door2","door","doorlight","Squall","Zell","Selphie","Rinoa","Quistis","Irvine","Edea","Angelo","Worker0","Worker1","Worker2","Worker3","Director","queen_spa","cardgamemaster"};
static const int kM_escouse1[] = {7,7,5,5,5,3,6,7,9,3,9,9,9,7,5,4,5,4,3,3,34};
static const unsigned short kW_bccent1a[] = {8455,10245,9475,9985,4,644,1283,1795,2307,2819,3331,3843,4356,4996,5635,6147,6660,7299,7812};
static const char* const kB_bccent1a[] = {"Director","Squall","Zell","Quistis","Rinoa","Selphie","Irvine","P089","Ghei1","Ghei2","Ghei3","P094","Dog","DrawPointSampleCode","Urakata","Eventline1","door","haikei"};
static const char* const kN_bccent1a[] = {"Eventline1","Door1","door","haikei","Director","Squall","Zell","Quistis","Rinoa","Selphie","Irvine","P089","Ghei1","Ghei2","Ghei3","P094","Dog","DrawPointSampleCode","Urakata"};
static const int kM_bccent1a[] = {7,5,3,1,4,4,3,3,3,3,3,3,4,4,3,3,4,3,4};
static const unsigned short kW_esview1[] = {13447,18949,19717,20481,20737,10,1419,2956,4611,5132,6796,8460,10117,10883,11395,11907,12419,12931,14498};
static const char* const kB_esview1[] = {"Squall","Zell","Selphie","Rinoa","Quistis","Irvine","Edea","EsterArmy1","EsterArmy2","RentaCar7","Lemousine","Angelo","Director","cardgamemaster","to_worldmap","door","raillight","walllight"};
static const char* const kN_esview1[] = {"to_worldmap","Door1","door","raillight","walllight","Squall","Zell","Selphie","Rinoa","Quistis","Irvine","Edea","EsterArmy1","EsterArmy2","RentaCar7","Lemousine","Angelo","Director","cardgamemaster"};
static const int kM_esview1[] = {7,5,5,1,1,10,11,12,3,12,12,12,5,3,3,3,3,3,34};
static const unsigned short kW_bcport2a[] = {7175,8199,9859,9220,10371,3,516,1155,1667,2179,2691,3203,3715,4227,4740,5379,5892,6532};
static const char* const kB_bcport2a[] = {"Director","Squall","Zell","Quistis","Rinoa","Selphie","Irvine","Dog","Ghei1","Ghei2","DrawPointSampleCode","Urakata","Urakata2","Eventline1","Eventline","door","sea","fune"};
static const char* const kN_bcport2a[] = {"Eventline1","Eventline","sea","door","fune","Director","Squall","Zell","Quistis","Rinoa","Selphie","Irvine","Dog","Ghei1","Ghei2","DrawPointSampleCode","Urakata","Urakata2"};
static const int kM_bcport2a[] = {7,7,3,4,3,3,4,3,3,3,3,3,3,3,4,3,4,4};
static const unsigned short kW_bcform1a[] = {15623,16643,17155,18179,17667,4,653,2441,3723,5259,6795,8331,9861,10632,11779,12296,13449,14726,18694};
static const char* const kB_bcform1a[] = {"Director","Squall","Zell","Quistis","Rinoa","Selphie","Irvine","P129","Raijin","Dog","Ghei1","Ghei2","Ghei3","kisha1","Eventline","train","sain","sain2","door"};
static const char* const kN_bcform1a[] = {"Eventline","train","sain","door","sain2","Director","Squall","Zell","Quistis","Rinoa","Selphie","Irvine","P129","Raijin","Dog","Ghei1","Ghei2","Ghei3","kisha1"};
static const int kM_bcform1a[] = {7,3,3,3,3,4,13,9,11,11,11,11,5,8,3,8,9,6,6};
static const unsigned short kW_ecoway1[] = {28033,28289,28545,28801,29057,29313,29569,29827,30339,30851,17,2321,4625,6930,9361,11665,13969,16262,17156,17795,18307,18819,19331,19845,20611,21123,21636,22281,23586,31362,31747,32259,32771,33283,33795};
static const char* const kB_ecoway1[] = {"Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Lifter","Woman","Mother","Jiji","Director","Timer","Scroll","Shake","info","Disp","atkmes","cardgamemaster","daiseki","haikei","sky","map1scroll","map2scroll","map3scroll","road","tube","light1","light2","light3","light4","light5","attackmap1","attackmap2","attackmap3"};
static const char* const kN_ecoway1[] = {"road","tube","light1","light2","light3","light4","light5","attackmap1","attackmap2","attackmap3","Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Lifter","Woman","Mother","Jiji","Director","Timer","Scroll","Shake","info","Disp","atkmes","cardgamemaster","daiseki","haikei","sky","map1scroll","map2scroll","map3scroll"};
static const int kM_ecoway1[] = {1,1,1,1,1,1,1,3,3,3,17,17,17,18,17,17,17,6,4,3,3,3,3,5,3,3,4,9,34,2,3,3,3,3,3};
static const unsigned short kW_ecenter1[] = {36359,37383,38407,39431,48385,48641,48901,49669,50437,51203,51715,52227,52737,52993,53251,53763,54275,38,5028,9762,14242,18722,23202,27682,32131,32643,33155,33667,34188,35843,40451,40963,41475,41988,42633,43938,54786,55171,55683,56195,56707,57219};
static const char* const kB_ecenter1[] = {"Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Soldier1","Soldier2","Woman","Man","Lifter","Director","Timer","Shake","info","Disp","atkmes","cardgamemaster","daiseki","map1scroll","map2scroll","map3scroll","haikei","sky","ChubuLine1","ChubuLine2","ChubuLine3","ScrollLine","road","tube","sigr","sigc","sigl","markr","markc","markl","arrow1","arrow2","attackmap1","attackmap2","attackmap3"};
static const char* const kN_ecenter1[] = {"ChubuLine1","ChubuLine2","ChubuLine3","ScrollLine","road","tube","sigr","sigc","sigl","markr","markc","markl","arrow1","arrow2","attackmap1","attackmap2","attackmap3","Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Soldier1","Soldier2","Woman","Man","Lifter","Director","Timer","Shake","info","Disp","atkmes","cardgamemaster","daiseki","map1scroll","map2scroll","map3scroll","haikei","sky"};
static const int kM_ecenter1[] = {7,7,7,7,1,1,5,5,5,3,3,3,1,1,3,3,3,38,36,34,34,34,34,34,3,3,3,3,12,3,3,3,3,4,9,34,2,3,3,3,3,3};
static const unsigned short kW_ecmway1[] = {33287,34311,35335,44289,44545,44805,45573,46341,47107,47619,48131,48641,48897,49153,49411,49923,50435,35,4643,9250,13718,16674,21154,25634,30083,30595,31116,32771,36355,36867,37379,37892,38537,39842,50946,51331,51843,52355,52867};
static const char* const kB_ecmway1[] = {"Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Soldier1","Soldier2","Lifter","Director","Timer","Shake","info","Disp","atkmes","cardgamemaster","daiseki","sky","map1scroll","map2scroll","map3scroll","ChubuLine1","ChubuLine2","ChubuLine3","road","tube","sigr","sigc","sigl","markr","markc","markl","arrow1","arrow2","light","attackmap1","attackmap2","attackmap3"};
static const char* const kN_ecmway1[] = {"ChubuLine1","ChubuLine2","ChubuLine3","road","tube","sigr","sigc","sigl","markr","markc","markl","arrow1","arrow2","light","attackmap1","attackmap2","attackmap3","Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Soldier1","Soldier2","Lifter","Director","Timer","Shake","info","Disp","atkmes","cardgamemaster","daiseki","sky","map1scroll","map2scroll","map3scroll"};
static const int kM_ecmway1[] = {7,7,7,1,1,5,5,5,3,3,3,1,1,1,3,3,3,35,35,34,22,34,34,34,3,3,12,3,3,3,3,4,9,34,2,3,3,3,3};
static const unsigned short kW_glgate1[] = {6023,15749,16517,17285,18053,18821,19589,20357,21125,21893,22661,23429,24197,24965,25733,26501,27269,28037,28805,29573,30341,31109,31877,32645,33413,34181,34949,14723,4,645,1412,2052,2693,3461,4227,4740,5380,7043,7555,8071,9091,9604,10274,15235};
static const char* const kB_glgate1[] = {"squall","zell","irvine","rinoa","selphie","quistis","fury","bus0","bus1","woman0","woman1","woman2","director0","director1","cardgamemaster","hito","eventline0","hitotati","hitoa","hitob","hitoc","hitod","hitoe","hitof","hitog","hitoh","hitoi","hitoj","hitok","hitol","hitom","hiton","hitoo","hitop","hitoq","hitor","hitos","hitot","hitou","hitov","hitow","hitox","hitoy","hitoz"};
static const char* const kN_glgate1[] = {"eventline0","hitoa","hitob","hitoc","hitod","hitoe","hitof","hitog","hitoh","hitoi","hitoj","hitok","hitol","hitom","hiton","hitoo","hitop","hitoq","hitor","hitos","hitot","hitou","hitov","hitow","hitox","hitoy","hitoz","hitotati","squall","zell","irvine","rinoa","selphie","quistis","fury","bus0","bus1","woman0","woman1","woman2","director0","director1","cardgamemaster","hito"};
static const int kM_glgate1[] = {7,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,4,5,4,4,5,5,3,4,4,3,3,7,3,4,34,3};
static const unsigned short kW_gltown1[] = {24193,24453,25221,25989,26757,28035,27523,29059,16,2192,4368,6544,8720,10896,13061,13829,14595,15107,15619,16131,16644,17283,17795,18307,18819,19331,19843,20357,21123,21638,22532,23171,23683,28547};
static const char* const kB_gltown1[] = {"squall","zell","irvine","rinoa","selphie","quistis","bus0","bus1","g_hei1","g_hei2","g_hei3","sanpo0","dog","ekiin0","ekiin1","g_hei0","g_hei4","sounddir0","director0","director1","fury","busdirector0","busdirector1","rightdown0woman","rightdown1woman","hito","kawa","hitoa","hitob","hitoc","hitod","ekiin","hitotati","map"};
static const char* const kN_gltown1[] = {"kawa","hitoa","hitob","hitoc","hitod","hitotati","ekiin","map","squall","zell","irvine","rinoa","selphie","quistis","bus0","bus1","g_hei1","g_hei2","g_hei3","sanpo0","dog","ekiin0","ekiin1","g_hei0","g_hei4","sounddir0","director0","director1","fury","busdirector0","busdirector1","rightdown0woman","rightdown1woman","hito"};
static const int kM_gltown1[] = {1,5,5,5,5,3,3,3,16,16,16,16,16,16,5,5,3,3,3,3,4,3,3,3,3,3,3,5,3,6,4,3,3,3};
static const unsigned short kW_ssmedi1[] = {6279,12549,11781,3,515,1027,1539,2051,2563,3075,3587,4099,4612,5251,5763,7330};
static const char* const kB_ssmedi1[] = {"squall","squallsp","irvine","rinoa","selphie","quistis","squallrinoa","man0","man1","director1","director0","savePoint","cardgamemaster","saveline0","door"};
static const char* const kN_ssmedi1[] = {"saveline0","Door1","door","squall","squallsp","irvine","rinoa","selphie","quistis","squallrinoa","man0","man1","director1","director0","savePoint","cardgamemaster"};
static const int kM_ssmedi1[] = {7,5,5,3,3,3,3,3,3,3,3,3,4,3,3,34};
static const unsigned short kW_emlobby2[] = {20229,20997,22531,23043,23555,24065,24321,24577,24833,25089,25345,19,2579,5139,7699,10259,12819,15379,17925,18691,19203,19715,21765};
static const char* const kB_emlobby2[] = {"Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Lifter","Timer","Drow","Director","wipecont","door","greenwipe","greentube","upperlight","yellowlight","greenlight","redlight","orangelight","bluelight","pipeshade"};
static const char* const kN_emlobby2[] = {"Door1","door","greenwipe","greentube","upperlight","yellowlight","greenlight","redlight","orangelight","bluelight","pipeshade","Squall","Zell","Quistis","Rinoa","Irvine","Selphie","Edea","Lifter","Timer","Drow","Director","wipecont"};
static const int kM_emlobby2[] = {5,5,3,3,3,1,1,1,1,1,1,19,19,19,19,19,19,19,5,3,3,3,5};
static const unsigned short kW_ebinhi1a[] = {8199,9735,10759,11783,12807,15493,13827,14339,14852,13,1795,2307,2819,3331,3843,4358,5255,6278,7171,7683,9219,16261};
static const char* const kB_ebinhi1a[] = {"squall","zell","selphie","quistis","rinoa","irvine","meka","raijin","fuujin","dic","mapkun","dp01","seigyo","evl01","ll01","ll02","ll03","ll04","kuren","light","door"};
static const char* const kN_ebinhi1a[] = {"evl01","ll01","ll02","ll03","ll04","Door1","kuren","light","door","squall","zell","selphie","quistis","rinoa","irvine","meka","raijin","fuujin","dic","mapkun","dp01","seigyo"};
static const int kM_ebinhi1a[] = {7,7,7,7,7,5,3,3,4,13,3,3,3,3,3,6,7,6,3,3,3,5};
static const unsigned short kW_febrdg1[] = {7431,8455,9479,10503,13573,15105,15365,7,1031,2055,3079,4103,5127,6148,6788,11523,12035,12547,13059,14341};
static const char* const kB_febrdg1[] = {"squall","zell","irvine","rinoa","selphie","quistis","runcheck0","solkey","timerdir0","sounddir0","director1","director0","bridgecont","brdgeoff0","brdgeon0","brdgeon1","lad0","bridge","door"};
static const char* const kN_febrdg1[] = {"brdgeoff0","brdgeon0","brdgeon1","lad0","Door1","bridge","door","squall","zell","irvine","rinoa","selphie","quistis","runcheck0","solkey","timerdir0","sounddir0","director1","director0","bridgecont"};
static const int kM_febrdg1[] = {7,7,7,7,5,1,5,7,7,7,7,7,7,4,4,3,3,3,3,5};
static const unsigned short kW_ffhole1[] = {10503,11527,13063,14087,15623,16647,18183,19207,20737,20993,21249,21507,12,1676,3340,5004,6668,8332,9987,12547,15107,17667,20227,22022,22913,23169,23425,23681,23937,24193,24449};
static const char* const kB_ffhole1[] = {"squall","zell","irvine","rinoa","selphie","quistis","gate0","gate1","gate2","gate3","director0","gate4","sea","chain1","chain2","chain3","chain4","chain5","chain6","gate0line","gateb0line","gate1line","gate1lineback","gate2line","gate2lineback","gate3line","gate3lineback","light1","light2","light3","light4"};
static const char* const kN_ffhole1[] = {"gate0line","gateb0line","gate1line","gate1lineback","gate2line","gate2lineback","gate3line","gate3lineback","light1","light2","light3","light4","squall","zell","irvine","rinoa","selphie","quistis","gate0","gate1","gate2","gate3","director0","gate4","sea","chain1","chain2","chain3","chain4","chain5","chain6"};
static const int kM_ffhole1[] = {7,7,7,7,7,7,7,7,1,1,1,3,12,12,12,12,12,12,3,3,3,3,3,6,1,1,1,1,1,1,1};
static const JsmOrderFixture JSM_ORDER_FIXTURES[] = {
    { "eccway11", 0,1,7,22,30, kW_eccway11, kB_eccway11, kN_eccway11, kM_eccway11 },
    { "escouse1", 2,2,2,15,21, kW_escouse1, kB_escouse1, kN_escouse1, kM_escouse1 },
    { "bccent1a", 1,1,2,15,19, kW_bccent1a, kB_bccent1a, kN_bccent1a, kM_bccent1a },
    { "esview1", 1,1,3,14,19, kW_esview1, kB_esview1, kN_esview1, kM_esview1 },
    { "bcport2a", 0,2,3,13,18, kW_bcport2a, kB_bcport2a, kN_bcport2a, kM_bcport2a },
    { "bcform1a", 0,1,4,14,19, kW_bcform1a, kB_bcform1a, kN_bcform1a, kM_bcform1a },
    { "ecoway1", 0,0,10,25,35, kW_ecoway1, kB_ecoway1, kN_ecoway1, kM_ecoway1 },
    { "ecenter1", 0,4,13,25,42, kW_ecenter1, kB_ecenter1, kN_ecenter1, kM_ecenter1 },
    { "ecmway1", 0,3,14,22,39, kW_ecmway1, kB_ecmway1, kN_ecmway1, kM_ecmway1 },
    { "glgate1", 0,1,27,16,44, kW_glgate1, kB_glgate1, kN_glgate1, kM_glgate1 },
    { "gltown1", 0,0,8,26,34, kW_gltown1, kB_gltown1, kN_gltown1, kM_gltown1 },
    { "ssmedi1", 1,1,1,13,16, kW_ssmedi1, kB_ssmedi1, kN_ssmedi1, kM_ssmedi1 },
    { "emlobby2", 1,0,10,12,23, kW_emlobby2, kB_emlobby2, kN_emlobby2, kM_emlobby2 },
    { "ebinhi1a", 1,5,3,13,22, kW_ebinhi1a, kB_ebinhi1a, kN_ebinhi1a, kM_ebinhi1a },
    { "febrdg1", 1,4,2,13,20, kW_febrdg1, kB_febrdg1, kN_febrdg1, kM_febrdg1 },
    { "ffhole1", 0,8,4,19,31, kW_ffhole1, kB_ffhole1, kN_ffhole1, kM_ffhole1 },
};
static const int JSM_ORDER_FIXTURE_COUNT = 16;
