#!/usr/bin/env python3
"""Emit tests/jsm_invistalk_fixtures.h from the real rgguest2 field files.

    python3 fieldsim/gen_invistalk_fixtures.py fielddata/out tests/jsm_invistalk_fixtures.h

rgguest2's `comp` is the Ragnarok terminal -- the one that tells the player how
the Propagator pairing works. Its init is SET3 / HIDE(0x061) / TALKON(0x057):
FF8 paints the terminal into the background art and leaves a hidden model behind
it to carry the talk target. The catalog's HIDE filter ate it.

Three variants of the same real file, so the scanner's rule is pinned from both
sides rather than only the side that happens to be true on this disc:
  REAL     -- untouched: HIDE and TALKON both in comp's init
  NO_TALK  -- comp's init TALKON overwritten with a literal push: HIDE alone
  NO_HIDE  -- comp's init HIDE overwritten with a literal push: TALKON alone
  LATE_TALK-- init TALKON removed AND a TALKON injected into comp's TALK method:
              the entity does call TALKON, just not while setting itself up. This
              is the variant that separates "in its init" from "anywhere in its
              scripts", and nothing on this disc separates them by itself.
A literal push (bit31 clear) is chosen because it is inert to the scanner, which
reads opcodes; nothing else about the file moves, so the three differ in exactly
the one word each name says.
"""
import struct, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ffield as F

HIDE, TALKON = 0x061, 0x057

def word_index(j, g, m, op):
    lo, hi = j.method_range(g, m)
    for i, w in enumerate(j.code[lo:hi]):
        if (w & 0xFF000000) == 0:
            if (w & 0xFFFFFF) == op: return lo + i
        elif (w >> 24) == op: return lo + i
    return None

def carr(name, b):
    out = ['static const unsigned char %s[%d] = {' % (name, len(b))]
    for i in range(0, len(b), 16):
        out.append('    ' + ','.join('0x%02X' % c for c in b[i:i+16]) + ',')
    out.append('};')
    return '\n'.join(out)

def main(root, out):
    F.DATA = root
    f = 'rgguest2'
    j = F.Jsm(f)
    gn = F.group_names(f, j)
    g = [i for i, n in enumerate(gn) if n == 'comp'][0]
    iHide = word_index(j, g, 0, HIDE)
    iTalk = word_index(j, g, 0, TALKON)
    if iHide is None or iTalk is None:
        raise SystemExit('rgguest2 comp init lost its HIDE/TALKON -- fixture is stale')
    raw = bytearray(F.rd(f, '.jsm'))
    sym = F.rd(f, '.sym')

    def patched(*idxs, **kw):
        b = bytearray(raw)
        for idx in idxs:
            struct.pack_into('<I', b, j.coff + idx * 4, 0x00000001)  # PSHN_L 1 -- inert
        for idx, word in kw.get('put', []):
            struct.pack_into('<I', b, j.coff + idx * 4, word)
        return bytes(b)

    # A word inside comp's TALK method (2) that is only a literal push, so
    # overwriting it changes what the scanner SEES and nothing it relies on.
    lo2, hi2 = j.method_range(g, 2)
    late = None
    for i, w in enumerate(j.code[lo2:hi2]):
        if (w >> 24) == 0x007: late = lo2 + i; break
    if late is None:
        raise SystemExit('comp method 2 has no literal push to borrow')

    parts = ['// GENERATED by fieldsim/gen_invistalk_fixtures.py -- do not edit.',
             '// Source: the real rgguest2 field files off the disc.',
             '// comp init HIDE at code word %d, TALKON at code word %d.' % (iHide, iTalk),
             '// LATE_TALK injects TALKON at code word %d, inside comp method 2.' % late,
             '#pragma once',
             carr('JSM_INVISTALK_SYM', sym),
             carr('JSM_INVISTALK_REAL', bytes(raw)),
             carr('JSM_INVISTALK_NO_TALK', patched(iTalk)),
             carr('JSM_INVISTALK_NO_HIDE', patched(iHide)),
             carr('JSM_INVISTALK_LATE_TALK', patched(iTalk, put=[(late, TALKON)]))]
    open(out, 'w').write('\n\n'.join(parts) + '\n')
    print('wrote %s (%d bytes jsm, %d bytes sym)' % (out, len(raw), len(sym)))

if __name__ == '__main__':
    if len(sys.argv) < 3: print(__doc__); sys.exit(2)
    main(sys.argv[1], sys.argv[2])
