#!/usr/bin/env python3
"""Generate tests/jsm_order_fixtures.h from the real field archive.

Each fixture carries the raw .jsm group words plus BOTH halves of the .sym:
the leading bare-name list and the method-section declaration order. Those two
halves are independent of each other, so a test that asserts
bare[symIdx[group]] == declName[group] is checking the order map against the
game's own data rather than against the derivation under test."""
import ffield, sys, os

FIELDS = ['eccway11','escouse1','bccent1a','esview1','bcport2a','bcform1a',
          'ecoway1','ecenter1','ecmway1','glgate1','gltown1','ssmedi1',
          'emlobby2','ebinhi1a','febrdg1','ffhole1']

def build(f):
    j = ffield.Jsm(f)
    nb = ffield.nbare(j)
    bare, _ = ffield.load_sym(f, nb)
    decl = ffield.sym_groups(f, nb)
    if len(bare) != nb or len(decl) != j.ngrp:
        return None
    rank = sorted(range(j.ngrp), key=lambda g: (j.groups[g][1], g))
    declName = [None]*j.ngrp; declMeth = [0]*j.ngrp
    for k, g in enumerate(rank):
        declName[g] = decl[k][0]; declMeth[g] = len(decl[k][1])
    return dict(name=f, nD=j.nD, nL=j.nL, nB=j.nB, nO=j.nO, ngrp=j.ngrp,
                words=[j.groups[g][0] | (j.groups[g][1] << 7) for g in range(j.ngrp)],
                bare=bare, declName=declName, declMeth=declMeth)

def cstr(s): return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')

def main(path):
    out = []
    for f in FIELDS:
        r = build(f)
        if r is None: print('  skipped %s (no usable SYM)' % f); continue
        out.append(r)
    L = ['// tests/jsm_order_fixtures.h -- GENERATED by fieldsim/gen_jsm_order_fixtures.py',
         '// Real .jsm group words and .sym contents, straight off the disc. Do not hand-edit.',
         '#pragma once',
         'struct JsmOrderFixture {',
         '    const char*  name;',
         '    int          nD, nL, nB, nO, ngrp;',
         '    const unsigned short* words;     // group words, ngrp of them',
         '    const char* const*    bare;      // SYM bare list, nO+nL+nB of them',
         '    const char* const*    declName;  // SYM method-section name, by GROUP',
         '    const int*            declMeth;  // that name\'s method count, by GROUP',
         '};']
    for r in out:
        n = r['name']
        L.append('static const unsigned short kW_%s[] = {%s};' % (n, ','.join(map(str, r['words']))))
        L.append('static const char* const kB_%s[] = {%s};' % (n, ','.join(cstr(x) for x in r['bare'])))
        L.append('static const char* const kN_%s[] = {%s};' % (n, ','.join(cstr(x) for x in r['declName'])))
        L.append('static const int kM_%s[] = {%s};' % (n, ','.join(map(str, r['declMeth']))))
    L.append('static const JsmOrderFixture JSM_ORDER_FIXTURES[] = {')
    for r in out:
        n = r['name']
        L.append('    { %s, %d,%d,%d,%d,%d, kW_%s, kB_%s, kN_%s, kM_%s },' %
                 (cstr(n), r['nD'], r['nL'], r['nB'], r['nO'], r['ngrp'], n, n, n, n))
    L.append('};')
    L.append('static const int JSM_ORDER_FIXTURE_COUNT = %d;' % len(out))
    open(path, 'w').write('\n'.join(L) + '\n')
    print('wrote %s with %d fixtures' % (path, len(out)))

if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else
         os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'tests', 'jsm_order_fixtures.h'))
