#!/usr/bin/env python3
"""Generate tests/jsm_decode_fixtures.h.

Two independent kinds of evidence, both straight off the disc:

  SET3 cases -- the raw instruction words of a SET3 placement plus the vertices
  of the walkmesh triangle the SET3's own INLINE PARAM names. The coordinates
  are popped values and the triangle is the parameter, so a decode that reads
  either one wrongly puts the point outside its triangle.

  MAPJUMP cases -- the raw words of a field transition plus the destination the
  game actually goes to. The Esthar ones are the strongest: Aaron played them
  and boarded Lunatic Pandora at the sites they name.
"""
import ffield, scan, fieldids, sys, os

FIELDS = ['eccway11','eccway21','ecmall1','ecoway1','ecenter1','bghall_1',
          'bgroom_1','glwater3','fhtown22','bcport2a']

def set3_cases(f, limit=6):
    j = ffield.Jsm(f)
    wm = ffield.Walkmesh(f)
    if not getattr(j,'ok',False) or not wm.ok: return []
    gn = ffield.group_names(f, j)
    out = []
    for g in range(j.ngrp):
        c,_ = j.groups[g]
        for m in range(-1, c):
            r = j.method_range(g, m)
            if not r: continue
            code = j.code[r[0]:r[1]]
            ins = scan.decode(code)
            for i,(op,par) in enumerate(ins):
                if op != 0x1E: continue
                if i < 3: continue
                if any(ins[i-k][0] != 0x07 for k in (1,2,3)): continue
                if par is None or par < 0 or par >= wm.n: continue
                x, y = ins[i-3][1], ins[i-2][1]
                if not wm.contains(par, x, y): continue
                out.append(dict(field=f, ent=gn[g] or '?', words=list(code[i-3:i+1]),
                                tri=par, verts=wm.tris[par]))
                if len(out) >= limit: return out
    return out

def mapjump_cases(f, limit=4):
    j = ffield.Jsm(f)
    if not getattr(j,'ok',False): return []
    gn = ffield.group_names(f, j)
    out=[]
    for g in range(j.ngrp):
        c,_ = j.groups[g]
        for m in range(-1, c):
            r = j.method_range(g, m)
            if not r: continue
            code = j.code[r[0]:r[1]]
            ins = scan.decode(code)
            for i,(op,par) in enumerate(ins):
                if op not in (0x29, 0x2A): continue
                n = 4 if op == 0x29 else 5
                if i < n: continue
                if any(ins[i-k][0] != 0x07 for k in range(1, n+1)): continue
                dest = ins[i-n][1]
                if dest is None or not (0 <= dest < len(fieldids.FIELD_INTERNAL)): continue
                out.append(dict(field=f, ent=gn[g] or '?', words=list(code[i-n:i+1]),
                                n=n, dest=dest, destName=fieldids.FIELD_INTERNAL[dest]))
                if len(out) >= limit: return out
    return out

def cstr(s): return '"%s"' % str(s).replace('\\','\\\\').replace('"','\\"')

def main(path):
    S=[]; M=[]
    for f in FIELDS:
        S += set3_cases(f); M += mapjump_cases(f)
    L=['// tests/jsm_decode_fixtures.h -- GENERATED by fieldsim/gen_jsm_decode_fixtures.py',
       '// Raw field-script words off the disc, with the walkmesh geometry and the',
       '// destinations they have to produce. Do not hand-edit.',
       '#pragma once',
       'struct Set3Case { const char* field; const char* ent;',
       '                  unsigned int w[4]; int tri; short v[9]; };',
       'struct JumpCase { const char* field; const char* ent; int n;',
       '                  unsigned int w[6]; int dest; const char* destName; };',
       'static const Set3Case SET3_CASES[] = {']
    for c in S:
        L.append('    { %s, %s, {%s}, %d, {%s} },' % (
            cstr(c['field']), cstr(c['ent']),
            ','.join('0x%08Xu'%w for w in c['words']), c['tri'],
            ','.join(str(v) for v in c['verts'])))
    L.append('};')
    L.append('static const int SET3_CASE_COUNT = %d;' % len(S))
    L.append('static const JumpCase JUMP_CASES[] = {')
    for c in M:
        w = c['words'] + [0]*(6-len(c['words']))
        L.append('    { %s, %s, %d, {%s}, %d, %s },' % (
            cstr(c['field']), cstr(c['ent']), c['n'],
            ','.join('0x%08Xu'%x for x in w), c['dest'], cstr(c['destName'])))
    L.append('};')
    L.append('static const int JUMP_CASE_COUNT = %d;' % len(M))
    open(path,'w').write('\n'.join(L)+'\n')
    print('wrote %s: %d SET3 cases, %d jump cases' % (path, len(S), len(M)))

if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv)>1 else
         os.path.join(os.path.dirname(os.path.abspath(__file__)),'..','tests','jsm_decode_fixtures.h'))
