// ff8_accessibility.h - Core header for FF8 Original PC Accessibility Mod
#pragma once

#include <windows.h>
#include <cstdint>
#include <string>

// ================================================================
// FF8 Original PC Accessibility Mod version
// Increment on every build change
// ================================================================
#define FF8OPC_VERSION "0.14.90.2"  // v0.14.90.2: Chapter 2 hotfix #5 — distance-based arrival decision. v0.14.90.1 BAT (clean save outside B-Garden) confirmed AD works end-to-end (11+ km drive, persist-through-battle, refined-coord capture); the earlier zero-movement BAT was caused by a save with the character wedged against geometry, correctly caught by stuck detection. Diagnostic logging stripped. BUT v0.14.90.1 BAT log surfaced a subtle bug: every world-map exit logs 'mode=2' (MODE_WORLDMAP). The pGameMode read happens at the moment we detect IsOnWorldMap flipped false, but at that exact tick the mode register hasn't transitioned to MODE_FIELD or MODE_SWIRL yet — it's still 2. Result: every exit goes through the 'pause and resume' branch, even arrivals. v0.14.90.2 replaces the pGameMode-based decision with a distance-based one: if s_driveLastDist < DRIVE_ARRIVED_ON_EXIT_DIST (1500) at exit → arrival announce + refined-coord capture; else → pause + auto-resume on re-entry. Battles fire anywhere; field entries only happen near a target by definition. Robust to mode-register timing. Architectural revert (in-exit-handler decision, not deferred), locomotion debounce, refined-coord capture, and sweep search are all retained from v0.14.90/v0.14.89/v0.14.87. BAT-validated. //

// v0.14.90.1: Diagnostic build for v0.14.90 zero-movement BAT. v0.14.90 BAT showed AD started a drive ('Driving to Balamb Garden. 11 kilometers.') but the character did not move at all — six consecutive 3-second stuck checks all reported 0 units. Added [DRIVE-KEY] log lines on every SetDriveKeys edge transition + [DRIVE-STEER] log lines every 2 seconds showing the steering decision's want-flags. Aaron's follow-up BAT with a different save (outside B-Garden, not wedged against geometry) showed AD working perfectly. The 'broken' BAT was a stuck save — v0.14.90's stuck detection correctly caught it and gave up after 18s of zero movement. Diagnostics stripped in v0.14.90.2. //

// v0.14.90: Chapter 2 hotfix #4 — architectural revert to v0.11.06 working baseline + locomotion debounce. v0.14.89 BAT failed badly: AD said 'Arrived near Balamb Garden' / 'Arrived near Balamb Town' without entering them. conversation_search of past chats v0.11.06-v0.11.10 revealed the working baseline used a fundamentally different architecture from v0.14.88-89: arrival is detected by reading pGameMode at the SAME tick as the world-map exit, deciding arrival vs interrupt right there — not in a deferred off-map block on the next poll. v0.14.90 reverts to that architecture: read pGameMode in the exit handler, MODE_FIELD/MODE_AFTER_BATTLE → arrival, anything else → pause-and-resume. Removed v0.14.87 vehicle proximity arrival ('Arrived near X') — it relied on s_lastVehicle which gets poisoned by transient locomotion-byte values (BAT showed mode 50 / mode 3 reading for 1 poll during foot travel). NEW: 4-poll debounce in CheckVehicleChange. Even canonical locomotion values must hold consistently across DEBOUNCE_POLLS consecutive polls before committing to s_lastVehicle. Real vehicle changes hold steady for many frames; transients last 1-2 polls. Refined-coord capture (v0.14.89) and sweep search (v0.14.87) retained. //

// v0.14.89: Empirical entry-coord capture. Parallel s_refinedX/Y/Has[LOCATION_COUNT] arrays alongside s_locations[]. When AD ends with a successful field entry within DRIVE_ARRIVED_ON_EXIT_DIST (1500) of catalog target, capture the player's last-known world-map (X, Y) as the empirical entry trigger position. StartAutoDrive checks this table first via FindLocationIndexByTargetCoords + s_refinedHas[locIdx] and prefers refined coord over catalog center for steering — making the second visit to a narrow-entrance location direct, no sweep required. In-memory only; persistent storage queued for v0.14.91+. //

// v0.14.88: Persist-through-battle. Random encounter mid-drive pauses AD silently; world-map re-entry resumes with 'Resuming drive to <Name>.' announcement. Re-arms stuck detection timer so the field/battle gap doesn't immediately trigger 'Stuck'. Drive target captured by VALUE (X, Y, name) at StartAutoDrive — survives arbitrary catalog rebuilds during the battle. //

// v0.14.87: Sweep search for narrow entrances + on-foot/vehicle arrival distinction. When on-foot AD enters final-approach zone (within DRIVE_FINAL_APPROACH_DIST=1000) but no entrance trigger fires within FINAL_APPROACH_TIMEOUT_MS=6000 ms (or stuck detection triggers in-zone), 6-phase alternating turn-then-walk sweep activates. Phases alternate right (odd) and left (even) turns of increasing duration (SWEEP_TURN_BASE_MS=800 + (phase-1)*200ms), walk forward SWEEP_WALK_DURATION_MS=3000 ms per phase. Field exit during any sub-state counts as arrival via Poll's exit handler; sweep exhaustion gives up with 'Could not find entrance.' Validated for Balamb Town in past chats v0.11.10. //

// v0.14.86: Initial AD restoration from past chats v0.11.05-v0.11.10. ~180 lines added to world_map.cpp: keybd_event-based key injection (VK_UP/LEFT/RIGHT, scan codes 0x48/0x4B/0x4D + KEYEVENTF_EXTENDEDKEY), idempotent SetDriveKeys (only generates events on state changes), bearing-relative steering (3 behaviors: ahead within 18°, diagonal 18-45°, side >45°), distance announces (one-shot 'Approaching X' at 3 km + periodic every 5s), stuck detection (DRIVE_STUCK_MAX=6 windows × DRIVE_STUCK_CHECK_INTERVAL_MS=3000 = 18s = give up), `\` key toggles AD on currently-selected catalog entry. Past chats v0.11.05-v0.11.07 discovered: the world map's input handler `worldmap_input_update_sub_559240` has its own input pipeline separate from the field's `engine_eval_keyboard_gamepad_input`, so the field-nav fake gamepad signal never reaches it. keybd_event injection at the OS level reaches both pipelines and works reliably on the world map. v0.11.08 BAT validated. //

// v0.14.85.3: Drop unvalidated mode 4 = Ragnarok mapping; whitelist canonical locomotion values; rule-class-triggered catalog rebuild. Aaron clarified after v0.14.85.2 sketch: he doesn't have Ragnarok in this save — the mode 4 read in the v0.14.85.1 BAT log was NOT a Ragnarok mount, it was a transient locomotion-byte read at a Fire Cavern field-transition moment. The 'mode 4 = Ragnarok' tag in v0.14.83 was Claude's assumption from an earlier BAT log labeled 'Ragnarok session,' never confirmed against actual gameplay. Per the research doc, Ragnarok is mode 50. Changes: GetVehicleType no longer maps mode 4 to Ragnarok (defaults to VEH_ON_FOOT for any non-canonical mode); GetVehicleName reports 'Unknown vehicle' for unrecognized modes; cars (32-40) share a single 'Car' name; new IsCanonicalLocomotion whitelist replaces v0.14.83's `vehicle > 4` guard with explicit canonical set {0, 3, 6, 31, 32-40, 48, 50} per the research doc — transients silenced at the source; new GetBfsRuleClass(VehicleType) returns 0 (land-only: foot/chocobo/car), 1 (ocean-allowed: Ship/Garden), 2 (no-filter: Ragnarok). The v0.14.85.2 rebuild trigger refined to compare rule class instead of full VehicleType, so foot ↔ car transitions don't trigger gratuitous rebuilds (both class 0, BFS result identical). //

// v0.14.85.2: Vehicle-change-triggered catalog rebuild. v0.14.85.1 BAT showed terrain + filter working at startup but the filter not re-applying on world-map re-entry after a brief field transition. Catalog only rebuilt on world-map enter/exit; vehicle changes mid-session didn't trigger a rebuild. Added VehicleType-change rebuild in CheckVehicleChange. //

// v0.14.85.1: Two failures, two fixes. (1) Terrain parser was structurally wrong. v0.14.85 log showed 'Grid built: 768 land, 0 ocean (of 768)' and 'From seg(19,20) veh=0: 768/768 segments reachable' — zero filtering. The flat-stride parser scanned 2304 polygons per segment from offset 0, but per the wmx.obj research doc each 36864-byte segment has a 68-byte header, then 16 variable-length blocks each with their own 4-byte header (poly_count, vert_count, norm_count, pad), then padding. Polygons live INSIDE blocks at offsets specified by the segment header. The flat scan read garbage bytes between blocks. Rewrote LoadTerrainGrid to walk the proper segment header → block headers → polygon arrays with bounds-guards. Result: 195 land + 573 ocean = 768 total, recognizable FF8 continents in the visual grid dump, ~473K real polygons. (2) Catalog used wrong coordinate system + had interior-only entries. Replaced wholesale with the canonical 38-entry set from `Plan & Research Documents/World Map Location Coordinates Research Findings.md`: 26 numbered FinalFantasyKingdom markers + 7 chocobo forests + 4 alien sites + Fire Cavern. //

// v0.14.85: Catalog reachability filter — initial reconstruction. ~265 lines added: WMX constants, VehicleType enum, terrain/reachability state, file I/O helpers, LZSS, WorldXToSegCol with the v0.11.16 +131072 X-offset fix, GetVehicleType, LoadTerrainGrid, ComputeReachability, BuildDistanceCatalog with deferred (0,0) build + reachability filter. BAT FAILED with two distinct flaws (parser + coords) addressed in v0.14.85.1. //

// v0.14.84: World Map nav post-BAT follow-up. v0.14.83 fixed regressions (vehicle spam + dead -/=/Backspace nav keys). BAT also surfaced two FURTHER missing pieces from before the v0.14.24 build damage: (1) entity catalog used to filter/sort by reachability, (2) the `\` key used to trigger auto-drive. Investigation: GitHub HEAD and earlier catch-up commits both contain the SAME minimal v0.11.16-baseline world_map.cpp — neither BFS terrain filtering nor auto-drive code has ever been pushed. Added `\` key placeholder (VK_OEM_5 → 'World map auto-drive is not yet implemented in this build.') so the keypress is not silent. //

// v0.14.83: World Map navigation regression fix. Two-bug repair stemming from the v0.14.24 build damage / v0.14.31 partial recovery. (1) WorldMap::HandleKeyPress was defined in world_map.cpp but never declared in world_map.h and never invoked. World map nav keys (- = Backspace) had been silently dead since the recovery. Replaced with a private static PollKeys() invoked at the end of Poll(). (2) Vehicle-change spam: the byte at WM_LOCOMOTION = 0x02040A5E reads canonical vehicle modes only at mount/dismount and drifts through animation-phase residue during locomotion. Added whitelist guard to CheckVehicleChange. //

// (Older changelogs archived to DEVNOTES_HISTORY.md — full v0.14.50-82 Scan TTS chapter, v0.14.45 SFX volume + audio ducking, v0.14.44 GF summon audio descriptions, v0.14.30s build recovery, etc. preserved there.)

#define FF8OPC_VERSION_DATE "2026-05-05"

// ============================================================================
// FF8 Runtime Address Resolution
// See ff8_addresses.h / ff8_addresses.cpp for the resolver that computes
// addresses at runtime using the same offset-chain technique as FFNx.
// ============================================================================
