// field_nav_names.inl — SYM name resolution, model names, field display names, BG classification
// Included from field_navigation.cpp. Do not compile independently.
// v0.12.18: Extracted from field_navigation.cpp for readability.

// ============================================================================
// SYM name → friendly display name resolution (v05.49)
// ============================================================================
//
// SYM names are Japanese developer shorthand for script entity slots.
// This function maps them to English-friendly names for TTS announcement.
// Strategy:
//   1. Check static table of known SYM→display mappings
//   2. Strip known suffixes (_u, _n, _s, _dummy, Dummy) that indicate variants
//   3. Capitalize the first letter
//   4. Return the cleaned name

// v0.12.10: Replaced hand-crafted 60-entry s_knownNames[] with comprehensive
// 148-entry ENTITY_DISPLAY_NAMES[] from entity_classifications.h,
// generated by surveying all 900 game fields.
// The old SymNameMapping struct is replaced by EntityDisplayName from the header.

// Resolve a SYM name to a friendly display name.
// Writes to outBuf (up to outBufSize-1 chars + null).
static void ResolveFriendlyName(const char* symName, char* outBuf, int outBufSize)
{
    if (!symName || symName[0] == '\0') {
        outBuf[0] = '\0';
        return;
    }

    // 1. Check comprehensive display name table (case-insensitive).
    for (const EntityDisplayName* m = ENTITY_DISPLAY_NAMES; m->sym != nullptr; m++) {
        if (_stricmp(symName, m->sym) == 0) {
            strncpy(outBuf, m->display, outBufSize - 1);
            outBuf[outBufSize - 1] = '\0';
            return;
        }
    }

    // 2. Not in table — clean up the raw name.
    //    Copy, strip trailing _u/_n/_s/Dummy suffixes, capitalize first letter.
    char temp[48];
    strncpy(temp, symName, 47);
    temp[47] = '\0';

    // Strip known suffixes.
    int len = (int)strlen(temp);
    if (len > 2 && (strcmp(temp + len - 2, "_u") == 0 ||
                    strcmp(temp + len - 2, "_n") == 0 ||
                    strcmp(temp + len - 2, "_s") == 0)) {
        temp[len - 2] = '\0';
        len -= 2;
    }
    if (len > 5 && _stricmp(temp + len - 5, "dummy") == 0) {
        temp[len - 5] = '\0';
        len -= 5;
    }

    // Capitalize first letter.
    if (temp[0] >= 'a' && temp[0] <= 'z')
        temp[0] = temp[0] - 'a' + 'A';

    // Replace underscores with spaces.
    for (int i = 0; i < len; i++) {
        if (temp[i] == '_') temp[i] = ' ';
    }

    strncpy(outBuf, temp, outBufSize - 1);
    outBuf[outBufSize - 1] = '\0';
}

// ============================================================================
// v05.53: Model-ID-based character name resolution
// ============================================================================
//
// SYM names are entity SLOT names, not character names. The engine reuses
// slots across scenes, so 'Squall_u' might actually hold Quistis's model.
// For main party characters (models 0-9), the model ID is authoritative.
// This function returns the character name for a known model ID, or nullptr
// if the model is a generic NPC (10+) that should use SYM-based naming.
//
// Model IDs confirmed from ENTDIAG dumps across multiple fields:
//   0=Squall, 1=Zell, 2=Irvine, 3=Quistis(casual), 4=Rinoa, 5=Selphie,
//   6=Seifer, 7=Edea, 8=Quistis(uniform), 9=Laguna(?)
//   10+=generic NPCs/students (use SYM name or "NPC")

static const char* ResolveNameByModelId(int16_t modelId)
{
    switch (modelId) {
        case 0:  return "Squall";
        case 1:  return "Zell";
        case 2:  return "Irvine";
        case 3:  return "Quistis";
        case 4:  return "Rinoa";
        case 5:  return "Selphie";
        case 6:  return "Seifer";
        case 7:  return "Edea";
        case 8:  return "Quistis";
        // 9 might be Laguna but needs confirmation
        default: return nullptr;  // generic NPC, use SYM name
    }
}

// ============================================================================
// v0.07.64: Field ID → human-readable display name lookup
// ============================================================================
// Uses the static FIELD_DISPLAY_NAMES[] table from field_display_names.h
// (982 entries, field IDs 0–981, disambiguated with sequential numbering).
// Returns the display name for a given field ID, or the internal field name
// as fallback if the ID is out of range.

static const char* GetFieldDisplayName(uint16_t fieldId)
{
    if (fieldId < FIELD_DISPLAY_NAMES_COUNT)
        return FIELD_DISPLAY_NAMES[fieldId];
    return nullptr;
}

// v0.07.66: Look up display name by internal field name (e.g. "bghall1a" -> "B-Garden - Hall 2").
// Searches FIELD_INTERNAL_NAMES[] for the match, returns corresponding FIELD_DISPLAY_NAMES[] entry.
// The FL-based index in FieldArchive is NOT the game's field ID, so we must search here.
static const char* GetFieldDisplayNameByInternalName(const char* internalName)
{
    if (!internalName) return nullptr;
    for (int i = 0; i < FIELD_DISPLAY_NAMES_COUNT; i++) {
        if (_stricmp(internalName, FIELD_INTERNAL_NAMES[i]) == 0)
            return FIELD_DISPLAY_NAMES[i];
    }
    return nullptr;
}

// ============================================================================
// v05.51: Background entity classification by SYM name
// ============================================================================
//
// Background entities have no model/talk/push flags. We classify them by name:
// - Known NPC names (characters, students, etc.) → ENT_BG_NPC
// - Known interactive objects (terminal, bulletin board) → ENT_BG_OBJECT
// - Known controllers/animations (cut, redlight, door, etc.) → skip
// - Unknown names → ENT_BG_NPC (default to showing them)

// Names that indicate a controller/animation entity — skip these.
// v0.12.10: Replaced hand-crafted 16-entry list with comprehensive
// 213-entry ENTITY_SKIP_NAMES[] from entity_classifications.h,
// generated by surveying all 900 game fields.

// Returns true if the SYM name indicates a controller/animation that should be skipped.
static bool IsBgControllerName(const char* symName)
{
    if (!symName || symName[0] == '\0') return true;  // unnamed = skip
    // Check comprehensive skip list from survey data.
    for (const char** p = ENTITY_SKIP_NAMES; *p; p++) {
        if (_stricmp(symName, *p) == 0) return true;
    }
    // Names containing "jump" are trigger zones.
    if (strstr(symName, "jump") || strstr(symName, "Jump")) return true;
    // Names starting with "to_" are exit triggers (handled by gateways).
    if (strncmp(symName, "to_", 3) == 0 || strncmp(symName, "To_", 3) == 0) return true;
    return false;
}

// Classify a background entity by its SYM name.
static EntityType ClassifyBgEntity(const char* symName)
{
    if (!symName || symName[0] == '\0') return ENT_UNKNOWN;
    // Check known objects in the display name table.
    for (const EntityDisplayName* m = ENTITY_DISPLAY_NAMES; m->sym != nullptr; m++) {
        if (_stricmp(symName, m->sym) == 0) {
            // If it resolves to "Terminal", "Bulletin Board", etc. → object
            if (_stricmp(m->display, "Terminal") == 0 ||
                _stricmp(m->display, "Bulletin Board") == 0 ||
                _stricmp(m->display, "Elevator") == 0 ||
                _stricmp(m->display, "Door") == 0 ||
                _stricmp(m->display, "Study Panel") == 0 ||
                _stricmp(m->display, "Desk") == 0 ||
                _stricmp(m->display, "Information") == 0 ||
                _stricmp(m->display, "Memo") == 0 ||
                _stricmp(m->display, "Newspaper") == 0 ||
                _stricmp(m->display, "Sign") == 0 ||
                _stricmp(m->display, "Book") == 0 ||
                _stricmp(m->display, "Directory") == 0)
                return ENT_BG_OBJECT;
            // Otherwise it's a named character/NPC.
            return ENT_BG_NPC;
        }
    }
    // Default: treat as NPC (shows up in navigation as interactable).
    return ENT_BG_NPC;
}

