// ============================================================================
// field_nav_duproom.inl -- duplicated-room phantom-exit suppression (v0.20.7)
// ============================================================================
// FF8 reuses one physical room (walkmesh) across several field files for
// different story states. A room's REAL navigable exits are INF gateways,
// present in the "normal" variant(s). A CUTSCENE variant of the same room has
// no gateways -- it only carries scripted MAPJUMPs that fire as scene
// transitions. Those MAPJUMPs decode to the same destinations as the gateway
// exits, so the catalog used to surface them as navigable "phantom" exits (e.g.
// Caraway's Mansion 2/5 announcing "Exit to Mansion 6" mid-briefing, when the
// real exit is a gateway that only exists in Mansion 1). Disassembly showed the
// phantom MAPJUMP is structurally identical to a real trapdoor (glprein1 'tobi':
// a REQ-heavy own-method MAPJUMP with no gateway), so no per-entity signal can
// tell them apart -- the reliable discriminator is the room duplication itself.
//
// THE RULE (fully general, data-driven): group every field by its walkmesh (a
// stable FNV-1a hash of the raw .id). For each room, note the destinations its
// gatewayed variant(s) reach. On a field, drop a scripted MAP_EXIT whose
// destination is one the room reaches through a real gateway in ANOTHER copy --
// unless THIS copy has its own local gateway there (then it is a real exit here,
// and the local-gateway guard in ComputeDupRoomSuppression keeps it).
//
// The table is AUTO-GENERATED from the field archive by
// Utilities/gen_duproom_table.py (committed) -- derived data, not hand-authored
// special cases; the code here is the general rule. Trapdoor-style unique
// scripted exits (glprein1, glclock1) are ABSENT from the table because no
// same-walkmesh sibling gateways to their destination, so they are never
// touched. The runtime log line "[duproom] field=... wmHash=..." lets a BAT
// confirm the hash the mod computes matches the offline table.
// ============================================================================

// Room (walkmesh FNV-1a-64 of .id) -> destination field IDs that a REAL INF
// gateway serves in some variant of that room.
static const struct { uint64_t wmHash; uint8_t destCount; uint16_t dests[8]; } s_dupRoomExits[] = {
    { 0x25b872308e65f6a8ULL, 2, { 125,126 } },                 // bcport1a
    { 0x528ac982f463bf54ULL, 1, { 140 } },                     // bg2f_1 / bg2f_1a
    { 0x2cf88dc71fb81fe9ULL, 6, { 137,138,143,144,232,233 } }, // bg2f_4
    { 0x42d01758171b9b17ULL, 2, { 149,151 } },                 // bgbook1b / bgbook_1
    { 0x764a3df0c2c1605fULL, 1, { 307 } },                     // doani1_2 / doani2_1 / doani2_2
    { 0x6ff25e66c2b1307fULL, 2, { 307,308 } },                 // domt3_1
    { 0x601e17be70a2332cULL, 1, { 349 } },                     // ebadele5
    { 0xbbbb56186a2f7bc3ULL, 1, { 372 } },                     // ebinmid6
    { 0x6b867b5001a96de6ULL, 2, { 28,470 } },                  // edview1 / edview1a / edview1b
    { 0xf04a578c007b5d91ULL, 6, { 481,482,483,484,485,486 } }, // eein2
    { 0x275d010716266662ULL, 3, { 478,479,480 } },             // eein21 / eein22 / eestone1
    { 0xc89ce29adf69ec2cULL, 1, { 869 } },                     // efpod1a
    { 0xac7376864b7b1a06ULL, 6, { 30,488,489,494,497,869 } },  // efview1a
    { 0xf2e997b0826c8563ULL, 1, { 498 } },                     // ehsea2
    { 0x33a8da5b9bba60a7ULL, 1, { 530 } },                     // emlabo1b
    { 0x90511581fcef9c86ULL, 1, { 573 } },                     // feroad2
    { 0x86c159b437c88545ULL, 1, { 726 } },                     // glfurin4 / glfurin5  (Caraway's Mansion 2/5 -> Mansion 6)
    { 0x607f8d89f44fc1b0ULL, 1, { 736 } },                     // glhtr1a
    { 0xe1d25033d3542428ULL, 2, { 752,756 } },                 // glsta3 / glsta4
    { 0x9b25fbe312288026ULL, 1, { 746 } },                     // glwitch2
    { 0xef7d6133054d03f6ULL, 2, { 774,778 } },                 // gmpark2
    { 0x4da0f92e0951d316ULL, 2, { 808,814 } },                 // gpbrdg1
    { 0x151eb98010290cc9ULL, 1, { 913 } },                     // tistud22
};
static const int s_dupRoomExitCount = (int)(sizeof(s_dupRoomExits) / sizeof(s_dupRoomExits[0]));

// v0.20.8: world-map STAGING fields -- fields the mod names wm* (ids 0..79) that NO
// INF gateway anywhere targets. You arrive on these ON the world map; you never walk
// into one through a field exit, so a scripted MAP_EXIT to one is a cutscene "leave to
// the world map" transition, not a navigable exit (Caraway's Mansion 1 'eventline2' ->
// wm60). The gatewayed wm* fields (the efview/edview world-map VIEW rooms, which you do
// walk on) are deliberately EXCLUDED. Generated by Utilities/gen_duproom_table.py.
static const uint16_t s_wmStagingFields[] = {
    0,2,5,8,9,11,12,13,17,21,26,27,31,33,34,35,36,37,38,39,44,46,47,48,49,50,51,
    52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79
};
static bool IsWorldMapStaging(uint16_t dest)
{
    for (size_t i = 0; i < sizeof(s_wmStagingFields) / sizeof(s_wmStagingFields[0]); i++)
        if (s_wmStagingFields[i] == dest) return true;
    return false;
}

// Precompute, at field load (after LoadINFGateways populated s_gateways), the
// scripted-exit destinations that are phantoms on THIS field: destinations the
// room reaches via a real gateway in a sibling copy, but which this field has no
// local gateway to. Result lives in s_dupSuppressDests / s_dupSuppressCount.
static void ComputeDupRoomSuppression(const char* fieldName)
{
    s_dupSuppressCount = 0;
    if (!fieldName || fieldName[0] == '(') return;
    uint64_t wmh = FieldArchive::WalkmeshHash(fieldName);
    if (!wmh) return;
    const int cap = (int)(sizeof(s_dupSuppressDests) / sizeof(s_dupSuppressDests[0]));
    bool matched = false;
    for (int r = 0; r < s_dupRoomExitCount; r++) {
        if (s_dupRoomExits[r].wmHash != wmh) continue;
        matched = true;
        for (int k = 0; k < s_dupRoomExits[r].destCount; k++) {
            uint16_t dest = s_dupRoomExits[r].dests[k];
            bool localGw = false;
            for (int g = 0; g < s_gatewayCount; g++)
                if (s_gateways[g].destFieldId == dest) { localGw = true; break; }
            if (!localGw && s_dupSuppressCount < cap)
                s_dupSuppressDests[s_dupSuppressCount++] = dest;
        }
        break;
    }
    if (matched)
        Log::Field("FieldNavigation: [duproom] field='%s' wmHash=%016llx matched room, suppressing %d phantom dest(s)",
                   fieldName, (unsigned long long)wmh, s_dupSuppressCount);
}
