// menu_card_data.inl -- GENERATED by offline/gen_cards.py. DO NOT EDIT.
//
// The 110 Triple Triad cards, lifted from FF8_EN.exe rather than typed:
//   values 0x00C74D00, stride 8, [0]=Top [1]=Bottom [2]=Left [3]=Right [4]=element
//   names  0x00C75074, u16 count + u16 offsets + FF8 glyph text
//
// The generator refuses to emit unless every card passes three checks: all four
// powers in 1..10, at most one element bit, and byte +5 (the game's own AI
// rating) equal to (T^2+B^2+L^2+R^2)/2 -- which is an INDEPENDENT confirmation
// that those four bytes really are the four powers, in those four positions.
//
// Spoken order is Top, Right, Bottom, Left (clockwise from the top), which is
// Aaron's request and matches how the card is read on screen.

#ifndef MENU_CARD_DATA_INCLUDED
#define MENU_CARD_DATA_INCLUDED

static const int CARD_COUNT = 110;

struct CardDef { const char* name; unsigned char top, right, bottom, left, elem; };
static const CardDef CARD_DEFS[CARD_COUNT] = {
    { "Geezard",  1,  4,  1,  5, 0x00 },   //   0  none
    { "Funguar",  5,  1,  1,  3, 0x00 },   //   1  none
    { "Bite Bug",  1,  3,  3,  5, 0x00 },   //   2  none
    { "Red Bat",  6,  1,  1,  2, 0x00 },   //   3  none
    { "Blobra",  2,  3,  1,  5, 0x00 },   //   4  none
    { "Gayla",  2,  1,  4,  4, 0x04 },   //   5  Thunder
    { "Gesper",  1,  5,  4,  1, 0x00 },   //   6  none
    { "Fastitocalon-F",  3,  5,  2,  1, 0x08 },   //   7  Earth
    { "Blood Soul",  2,  1,  6,  1, 0x00 },   //   8  none
    { "Caterchipillar",  4,  2,  4,  3, 0x00 },   //   9  none
    { "Cockatrice",  2,  1,  2,  6, 0x04 },   //  10  Thunder
    { "Grat",  7,  1,  3,  1, 0x00 },   //  11  none
    { "Buel",  6,  2,  2,  3, 0x00 },   //  12  none
    { "Mesmerize",  5,  3,  3,  4, 0x00 },   //  13  none
    { "Glacial Eye",  6,  1,  4,  3, 0x02 },   //  14  Ice
    { "Belhelmel",  3,  4,  5,  3, 0x00 },   //  15  none
    { "Thrustaevis",  5,  3,  2,  5, 0x20 },   //  16  Wind
    { "Anacondaur",  5,  1,  3,  5, 0x10 },   //  17  Poison
    { "Creeps",  5,  2,  5,  2, 0x04 },   //  18  Thunder
    { "Grendel",  4,  4,  5,  2, 0x04 },   //  19  Thunder
    { "Jelleye",  3,  2,  1,  7, 0x00 },   //  20  none
    { "Grand Mantis",  5,  2,  5,  3, 0x00 },   //  21  none
    { "Forbidden",  6,  6,  3,  2, 0x00 },   //  22  none
    { "Armadodo",  6,  3,  1,  6, 0x08 },   //  23  Earth
    { "Tri-Face",  3,  5,  5,  5, 0x10 },   //  24  Poison
    { "Fastitocalon",  7,  5,  1,  3, 0x08 },   //  25  Earth
    { "Snow Lion",  7,  1,  5,  3, 0x02 },   //  26  Ice
    { "Ochu",  5,  6,  3,  3, 0x00 },   //  27  none
    { "SAM08G",  5,  6,  2,  4, 0x01 },   //  28  Fire
    { "Death Claw",  4,  4,  7,  2, 0x01 },   //  29  Fire
    { "Cactuar",  6,  2,  6,  3, 0x00 },   //  30  none
    { "Tonberry",  3,  6,  4,  4, 0x00 },   //  31  none
    { "Abyss Worm",  7,  2,  3,  5, 0x08 },   //  32  Earth
    { "Turtapod",  2,  3,  6,  7, 0x00 },   //  33  none
    { "Vysage",  6,  5,  4,  5, 0x00 },   //  34  none
    { "T-Rexaur",  4,  6,  2,  7, 0x00 },   //  35  none
    { "Bomb",  2,  7,  6,  3, 0x01 },   //  36  Fire
    { "Blitz",  1,  6,  4,  7, 0x04 },   //  37  Thunder
    { "Wendigo",  7,  3,  1,  6, 0x00 },   //  38  none
    { "Torama",  7,  4,  4,  4, 0x00 },   //  39  none
    { "Imp",  3,  7,  3,  6, 0x00 },   //  40  none
    { "Blue Dragon",  6,  2,  7,  3, 0x10 },   //  41  Poison
    { "Adamantoise",  4,  5,  5,  6, 0x08 },   //  42  Earth
    { "Hexadragon",  7,  5,  4,  3, 0x01 },   //  43  Fire
    { "Iron Giant",  6,  5,  6,  5, 0x00 },   //  44  none
    { "Behemoth",  3,  6,  5,  7, 0x00 },   //  45  none
    { "Chimera",  7,  6,  5,  3, 0x40 },   //  46  Water
    { "PuPu",  3, 10,  2,  1, 0x00 },   //  47  none
    { "Elastoid",  6,  2,  6,  7, 0x00 },   //  48  none
    { "GIM47N",  5,  5,  7,  4, 0x00 },   //  49  none
    { "Malboro",  7,  7,  4,  2, 0x10 },   //  50  Poison
    { "Ruby Dragon",  7,  2,  7,  4, 0x01 },   //  51  Fire
    { "Elnoyle",  5,  3,  7,  6, 0x00 },   //  52  none
    { "Tonberry King",  4,  6,  7,  4, 0x00 },   //  53  none
    { "Wedge, Biggs",  6,  6,  2,  7, 0x00 },   //  54  none
    { "Fujin, Raijin",  2,  8,  8,  4, 0x00 },   //  55  none
    { "Elvoret",  7,  8,  3,  4, 0x20 },   //  56  Wind
    { "X-ATM092",  4,  8,  7,  3, 0x00 },   //  57  none
    { "Granaldo",  7,  2,  8,  5, 0x00 },   //  58  none
    { "Gerogero",  1,  8,  8,  3, 0x10 },   //  59  Poison
    { "Iguion",  8,  2,  8,  2, 0x00 },   //  60  none
    { "Abadon",  6,  8,  4,  5, 0x00 },   //  61  none
    { "Trauma",  4,  8,  5,  6, 0x00 },   //  62  none
    { "Oilboyle",  1,  8,  4,  8, 0x00 },   //  63  none
    { "Shumi Tribe",  6,  5,  8,  4, 0x00 },   //  64  none
    { "Krysta",  7,  5,  8,  1, 0x00 },   //  65  none
    { "Propagator",  8,  4,  4,  8, 0x00 },   //  66  none
    { "Jumbo Cactuar",  8,  8,  4,  4, 0x00 },   //  67  none
    { "Tri-Point",  8,  5,  2,  8, 0x04 },   //  68  Thunder
    { "Gargantua",  5,  6,  6,  8, 0x00 },   //  69  none
    { "Mobile Type 8",  8,  6,  7,  3, 0x00 },   //  70  none
    { "Sphinxara",  8,  3,  5,  8, 0x00 },   //  71  none
    { "Tiamat",  8,  8,  5,  4, 0x00 },   //  72  none
    { "BGH251F2",  5,  7,  8,  5, 0x00 },   //  73  none
    { "Red Giant",  6,  8,  4,  7, 0x00 },   //  74  none
    { "Catoblepas",  1,  8,  7,  7, 0x00 },   //  75  none
    { "Ultima Weapon",  7,  7,  2,  8, 0x00 },   //  76  none
    { "Chubby Chocobo",  4,  4,  8,  9, 0x00 },   //  77  none
    { "Angelo",  9,  6,  7,  3, 0x00 },   //  78  none
    { "Gilgamesh",  3,  7,  9,  6, 0x00 },   //  79  none
    { "MiniMog",  9,  3,  9,  2, 0x00 },   //  80  none
    { "Chicobo",  9,  4,  8,  4, 0x00 },   //  81  none
    { "Quezacotl",  2,  9,  9,  4, 0x04 },   //  82  Thunder
    { "Shiva",  6,  7,  4,  9, 0x02 },   //  83  Ice
    { "Ifrit",  9,  6,  2,  8, 0x01 },   //  84  Fire
    { "Siren",  8,  9,  6,  2, 0x00 },   //  85  none
    { "Sacred",  5,  1,  9,  9, 0x08 },   //  86  Earth
    { "Minotaur",  9,  5,  2,  9, 0x08 },   //  87  Earth
    { "Carbuncle",  8,  4, 10,  4, 0x00 },   //  88  none
    { "Diablos",  5, 10,  8,  3, 0x00 },   //  89  none
    { "Leviathan",  7, 10,  1,  7, 0x40 },   //  90  Water
    { "Odin",  8, 10,  3,  5, 0x00 },   //  91  none
    { "Pandemona", 10,  1,  7,  7, 0x20 },   //  92  Wind
    { "Cerberus",  7,  4,  6, 10, 0x00 },   //  93  none
    { "Alexander",  9, 10,  4,  2, 0x80 },   //  94  Holy
    { "Phoenix",  7,  2,  7, 10, 0x01 },   //  95  Fire
    { "Bahamut", 10,  8,  2,  6, 0x00 },   //  96  none
    { "Doomtrain",  3,  1, 10, 10, 0x10 },   //  97  Poison
    { "Eden",  4,  4,  9, 10, 0x00 },   //  98  none
    { "Ward", 10,  7,  2,  8, 0x00 },   //  99  none
    { "Kiros",  6,  7,  6, 10, 0x00 },   // 100  none
    { "Laguna",  5, 10,  3,  9, 0x00 },   // 101  none
    { "Selphie", 10,  8,  6,  4, 0x00 },   // 102  none
    { "Quistis",  9,  6, 10,  2, 0x00 },   // 103  none
    { "Irvine",  2,  6,  9, 10, 0x00 },   // 104  none
    { "Zell",  8,  5, 10,  6, 0x00 },   // 105  none
    { "Rinoa",  4, 10,  2, 10, 0x00 },   // 106  none
    { "Edea", 10, 10,  3,  3, 0x00 },   // 107  none
    { "Seifer",  6,  9, 10,  4, 0x00 },   // 108  none
    { "Squall", 10,  4,  6,  9, 0x00 },   // 109  none
};

// The "MONSTER" line under the card: which monster carries it, or the pair
// that play it at levels 6-7. Empty for the 33 rare cards, whose line is the
// dynamic "AREA" instead. From [0x00B96500] = 0x00C75524.
static const char* const CARD_SOURCES[CARD_COUNT] = {
    "Geezard",                      //   0 Geezard
    "Funguar",                      //   1 Funguar
    "Bite Bug",                     //   2 Bite Bug
    "Red Bat",                      //   3 Red Bat
    "Blobra",                       //   4 Blobra
    "Gayla",                        //   5 Gayla
    "Gesper",                       //   6 Gesper
    "Fastitocalon-F",               //   7 Fastitocalon-F
    "Blood Soul",                   //   8 Blood Soul
    "Caterchipillar",               //   9 Caterchipillar
    "Cockatrice",                   //  10 Cockatrice
    "Grat",                         //  11 Grat
    "Buel",                         //  12 Buel
    "Mesmerize",                    //  13 Mesmerize
    "Glacial Eye",                  //  14 Glacial Eye
    "Belhelmel",                    //  15 Belhelmel
    "Thrustaevis",                  //  16 Thrustaevis
    "Anacondaur",                   //  17 Anacondaur
    "Creeps",                       //  18 Creeps
    "Grendel",                      //  19 Grendel
    "Jelleye",                      //  20 Jelleye
    "Grand Mantis",                 //  21 Grand Mantis
    "Forbidden",                    //  22 Forbidden
    "Armadodo",                     //  23 Armadodo
    "Tri-Face",                     //  24 Tri-Face
    "Fastitocalon",                 //  25 Fastitocalon
    "Snow Lion",                    //  26 Snow Lion
    "Ochu",                         //  27 Ochu
    "SAM08G",                       //  28 SAM08G
    "Death Claw",                   //  29 Death Claw
    "Cactuar",                      //  30 Cactuar
    "Tonberry",                     //  31 Tonberry
    "Abyss Worm",                   //  32 Abyss Worm
    "Turtapod",                     //  33 Turtapod
    "Vysage,Lefty,Righty",          //  34 Vysage
    "T-Rexaur",                     //  35 T-Rexaur
    "Bomb",                         //  36 Bomb
    "Blitz",                        //  37 Blitz
    "Wendigo",                      //  38 Wendigo
    "Torama",                       //  39 Torama
    "Imp",                          //  40 Imp
    "Blue Dragon",                  //  41 Blue Dragon
    "Adamantoise",                  //  42 Adamantoise
    "Hexadragon",                   //  43 Hexadragon
    "Iron Giant",                   //  44 Iron Giant
    "Behemoth",                     //  45 Behemoth
    "Chimera",                      //  46 Chimera
    "PuPu",                         //  47 PuPu
    "Elastoid",                     //  48 Elastoid
    "GIM47N",                       //  49 GIM47N
    "Malboro",                      //  50 Malboro
    "Ruby Dragon",                  //  51 Ruby Dragon
    "Elnoyle",                      //  52 Elnoyle
    "Fastitocalon, Malboro",        //  53 Tonberry King
    "Snow Lion, Funguar",           //  54 Wedge, Biggs
    "Iron Giant, Jelleye",          //  55 Fujin, Raijin
    "Ochu, Bite Bug",               //  56 Elvoret
    "SAM08G, Red Bat",              //  57 X-ATM092
    "Death Claw, Blobra",           //  58 Granaldo
    "Cactuar, Gayla",               //  59 Gerogero
    "Tonberry, Gesper",             //  60 Iguion
    "Abyss Worm, Blood Soul",       //  61 Abadon
    "Turtapod, Caterchipillar",     //  62 Trauma
    "GIM47N, Cockatrice",           //  63 Oilboyle
    "T-Rexaur, Grat",               //  64 Shumi Tribe
    "Bomb, Buel",                   //  65 Krysta
    "Blitz, Mesmerize",             //  66 Propagator
    "Wendigo, Glacial Eye",         //  67 Jumbo Cactuar
    "Torama, Belhelmel",            //  68 Tri-Point
    "Imp, Thrustaevis",             //  69 Gargantua
    "Blue Dragon, Anacondaur",      //  70 Mobile Type 8
    "Adamantoise, Creeps",          //  71 Sphinxara
    "Hexadragon, Grendel",          //  72 Tiamat
    "Behemoth, Grand Mantis",       //  73 BGH251F2
    "Chimera, Forbidden",           //  74 Red Giant
    "Elnoyle, Armadodo",            //  75 Catoblepas
    "Elastoid, Tri-Face",           //  76 Ultima Weapon
    "",                             //  77 Chubby Chocobo
    "",                             //  78 Angelo
    "",                             //  79 Gilgamesh
    "",                             //  80 MiniMog
    "",                             //  81 Chicobo
    "",                             //  82 Quezacotl
    "",                             //  83 Shiva
    "",                             //  84 Ifrit
    "",                             //  85 Siren
    "",                             //  86 Sacred
    "",                             //  87 Minotaur
    "",                             //  88 Carbuncle
    "",                             //  89 Diablos
    "",                             //  90 Leviathan
    "",                             //  91 Odin
    "",                             //  92 Pandemona
    "",                             //  93 Cerberus
    "",                             //  94 Alexander
    "",                             //  95 Phoenix
    "",                             //  96 Bahamut
    "",                             //  97 Doomtrain
    "",                             //  98 Eden
    "",                             //  99 Ward
    "",                             // 100 Kiros
    "",                             // 101 Laguna
    "",                             // 102 Selphie
    "",                             // 103 Quistis
    "",                             // 104 Irvine
    "",                             // 105 Zell
    "",                             // 106 Rinoa
    "",                             // 107 Edea
    "",                             // 108 Seifer
    "",                             // 109 Squall
};

static const char* const CARD_ELEMENTS[8] = {
    "Fire", "Ice", "Thunder", "Earth", "Poison", "Wind", "Water", "Holy"
};

#endif // MENU_CARD_DATA_INCLUDED
