// rag_landing_table.inl -- GENERATED by offline/gen_rag_table.py. Do not edit.
//
// Where the Ragnarok sets down for each world-map destination.
//
// The airship has no movement mask at all -- 0x53E6B0 falls through to
// `return 1` for vehicle 0x32, so it flies over everything and there is nothing
// to route around. The only question the world map asks about it is where it
// may SET DOWN, and that is a different bit on a different byte: 0x53E730 reads
// (typeTriple >> 8) & 0x80, i.e. poly[14] bit 7.
//
// Two kinds of row:
//
//   RAG_PAD   the destination IS a landing pad -- fly to the spot and land on
//             it. Identified by the game's own data rather than by hand: a
//             record in the wmsetus location table that is landable and NOT
//             foot-walkable. Exactly 3 records in the whole table qualify:
//   #13  (   20480,   -2560)  h=  -500
//   #21  ( -118784,   86016)  h=  -868
//   #27  (   54791,    5650)  h= -1849
//             ...which are Fisherman's Horizon, the Deep Sea Research Center
//             and the Esthar Airstation -- the three Aaron named.
//
//   RAG_WALK  land as close as possible and walk. The cell must be landable,
//             foot-walkable, and foot-connected to the destination marker under
//             the engine's own step gate (|dH| >= 200 refuses), so the landing
//             is never across a strait from the place it serves.
//
// Distances are the walk left after landing, in world units.
static const RagLanding RAG_LANDINGS[] = {
    { "Balamb Garden",                24448,   -29312,    159, RAG_WALK,   320,   -675,   576 },   // margin 256; nearest cell with 576 units of landable ground all round (measured on the polygons, not the grid)
    { "Balamb Town",                  14464,   -27008,   1236, RAG_WALK,   290,   -447,   546 },   // margin 256; nearest cell with 546 units of landable ground all round (measured on the polygons, not the grid)
    { "Dollet",                      -17024,   -39808,   1434, RAG_WALK,   347,   -603,   603 },   // margin 256; nearest cell with 603 units of landable ground all round (measured on the polygons, not the grid)
    { "Timber",                      -23680,    -4992,   1123, RAG_WALK,   448,   -642,   704 },   // margin 256; nearest cell with 704 units of landable ground all round (measured on the polygons, not the grid)
    { "Galbadia Garden",             -37504,   -24960,    107, RAG_WALK,   294,   -613,   550 },   // margin 256; nearest cell with 550 units of landable ground all round (measured on the polygons, not the grid)
    { "Galbadia Station",            -37504,   -24960,    904, RAG_WALK,   294,   -613,   550 },   // margin 256; nearest cell with 550 units of landable ground all round (measured on the polygons, not the grid)
    { "Deling City",                 -62592,   -28032,    999, RAG_WALK,   448,   -829,   704 },   // margin 256; nearest cell with 704 units of landable ground all round (measured on the polygons, not the grid)
    { "Tomb of the Unknown King",    -44160,   -36480,   1691, RAG_WALK,   448,   -318,   704 },   // margin 256; nearest cell with 704 units of landable ground all round (measured on the polygons, not the grid)
    { "D-District Prison",           -55424,    -3968,    881, RAG_WALK,   448,   -166,   704 },   // margin 256; nearest cell with 704 units of landable ground all round (measured on the polygons, not the grid)
    { "Galbadia Missile Base",       -71808,   -15488,    153, RAG_WALK,   448,   -364,   704 },   // margin 256; nearest cell with 704 units of landable ground all round (measured on the polygons, not the grid)
    { "Fisherman's Horizon",          20480,    -2560,      0, RAG_PAD,    512,    -91,   889 },   // margin 377; the game's own record 13, landable and not walkable
    { "Trabia Garden",                48000,   -57984,    893, RAG_WALK,   412,   -834,   668 },   // margin 256; nearest cell with 668 units of landable ground all round (measured on the polygons, not the grid)
    { "Edea's House",                -28288,    68736,   1564, RAG_WALK,   377,   -308,   633 },   // margin 256; nearest cell with 633 units of landable ground all round (measured on the polygons, not the grid)
    { "White SeeD Ship",             -18816,    45696,   1557, RAG_WALK,   294,   -413,   550 },   // margin 256; nearest cell with 550 units of landable ground all round (measured on the polygons, not the grid)
    { "Great Salt Lake",              49536,    -3456,    849, RAG_WALK,   377,   -407,   633 },   // margin 256; nearest cell with 633 units of landable ground all round (measured on the polygons, not the grid)
    { "Esthar City",                  54791,     5650,   8249, RAG_PAD,    369,  -1349,   465 },   // margin 96; reached by landing at the Esthar Airstation (record 27); the city's own ground has no landable cell
    { "Lunatic Pandora Lab",          79488,    -9088,     57, RAG_WALK,   374,   -547,   630 },   // margin 256; nearest cell with 630 units of landable ground all round (measured on the polygons, not the grid)
    { "Lunar Gate",                   87936,     7808,    102, RAG_WALK,   512,   -257,  1024 },   // margin 512; nearest cell with 1024 units of landable ground all round (measured on the polygons, not the grid)
    { "Sorceress Memorial",           81536,    11904,     42, RAG_WALK,   512,   -523,  1024 },   // margin 512; nearest cell with 1024 units of landable ground all round (measured on the polygons, not the grid)
    { "Shumi Village",                12928,   -82816,   1168, RAG_WALK,   374,   -891,   630 },   // margin 256; nearest cell with 630 units of landable ground all round (measured on the polygons, not the grid)
    { "Mobile Galbadia Garden",      -24960,    65664,     99, RAG_WALK,   512,   -393,  1024 },   // margin 512; nearest cell with 1024 units of landable ground all round (measured on the polygons, not the grid)
    { "Winhill",                     -50816,     5248,   1196, RAG_WALK,   316,   -399,   572 },   // margin 256; nearest cell with 572 units of landable ground all round (measured on the polygons, not the grid)
    { "Centra Ruins",                  6784,    54144,   1146, RAG_WALK,   448,   -528,   704 },   // margin 256; nearest cell with 704 units of landable ground all round (measured on the polygons, not the grid)
    { "Deep Sea Research Center",   -118784,    86016,    354, RAG_PAD,    288,   -368,   384 },   // margin 96; the game's own record 21, landable and not walkable
    { "Cactuar Island",               54912,    62080,    113, RAG_WALK,   512,   -590,  1024 },   // margin 512; nearest cell with 1024 units of landable ground all round (measured on the polygons, not the grid)
    { "Tears' Point",                 83072,    31872,     51, RAG_WALK,   512,   -319,   770 },   // margin 258; nearest cell with 770 units of landable ground all round (measured on the polygons, not the grid)
    { "Island Closest to Hell",     -105088,    -3712,    102, RAG_WALK,   512,   -479,  1024 },   // margin 512; nearest cell with 1024 units of landable ground all round (measured on the polygons, not the grid)
    { "Island Closest to Heaven",    102272,   -53120,     43, RAG_WALK,   512,   -468,  1024 },   // margin 512; nearest cell with 1024 units of landable ground all round (measured on the polygons, not the grid)
    { "Chocobo Forest 1",             10624,   -64640,   1210, RAG_WALK,   290,   -577,   546 },   // margin 256; nearest cell with 546 units of landable ground all round (measured on the polygons, not the grid)
    { "Chocobo Forest 2",             11904,   -82048,   1425, RAG_WALK,   459,   -925,   715 },   // margin 256; nearest cell with 715 units of landable ground all round (measured on the polygons, not the grid)
    { "Chocobo Forest 3",             50560,    -5248,   1854, RAG_WALK,   290,   -472,   546 },   // margin 256; nearest cell with 546 units of landable ground all round (measured on the polygons, not the grid)
    { "Chocobo Forest 4",             97920,   -50560,   2404, RAG_WALK,   290,  -1471,   546 },   // margin 256; nearest cell with 546 units of landable ground all round (measured on the polygons, not the grid)
    { "Chocobo Forest 5",             17024,    23168,   1210, RAG_WALK,   402,   -473,   658 },   // margin 256; nearest cell with 658 units of landable ground all round (measured on the polygons, not the grid)
    { "Chocobo Forest 6",             45184,    77440,   1363, RAG_WALK,   334,   -315,   590 },   // margin 256; nearest cell with 590 units of landable ground all round (measured on the polygons, not the grid)
    { "Chocobo Forest 7",            -21376,    67712,   1267, RAG_WALK,   377,   -446,   633 },   // margin 256; nearest cell with 633 units of landable ground all round (measured on the polygons, not the grid)
    { "Alien Ship 1",                 79744,   -61312,    127, RAG_WALK,   512,   -440,   841 },   // margin 329; nearest cell with 841 units of landable ground all round (measured on the polygons, not the grid)
    { "Alien Ship 2",                 40576,    54656,     81, RAG_WALK,   512,   -495,  1024 },   // margin 512; nearest cell with 1024 units of landable ground all round (measured on the polygons, not the grid)
    { "Alien Ship 3",                -14208,    -9088,   1679, RAG_WALK,   290,   -139,   546 },   // margin 256; nearest cell with 546 units of landable ground all round (measured on the polygons, not the grid)
    { "Alien Ship 4",                -48768,     5760,     61, RAG_WALK,   512,   -471,   944 },   // margin 432; nearest cell with 944 units of landable ground all round (measured on the polygons, not the grid)
    { "Fire Cavern",                  29056,   -28032,   1740, RAG_WALK,   316,   -579,   572 },   // margin 256; nearest cell with 572 units of landable ground all round (measured on the polygons, not the grid)
};
static const int RAG_LANDING_COUNT = (int)(sizeof(RAG_LANDINGS) / sizeof(RAG_LANDINGS[0]));
