// world_map_routenet.inl -- GENERATED by offline/gen_routenet.py (v0.18.3.211).
// Precomputed VALIDATED route network: nodes = decoded entry aims; edges =
// exact max-clearance polylines validated by the BAT208 stateful engine
// replica + full executor simulation in BOTH directions (offline/ROUTENET.md).
// DATA SECTION (regenerate with: python3 offline/gen_routenet.py ... --emit).
// v0.18.3.211: the Galbadia pass edge is GONE (proven impassable in the .210
// live BAT); Timber/Dollet traffic routes east over the split .209
// Dollet<->Timber corridor via two new junctions (Yaulny Plains at the
// mountain-belt crossing NE of G-Garden, Hasberry Plains at the Dollet
// mouth outside Dollet's firing bbox). Full matrix 20/20 arrived.

static const int ROUTENET_NODE_COUNT = 13;
static const char* const s_rnNodeNames[13] = {
    "Balamb Garden",
    "Balamb Town",
    "Dollet",
    "Fire Cavern",
    "GG East Plains",
    "GG West Plains",
    "Galbadia Garden",
    "Galbadia Station",
    "Hasberry Plains",
    "Lunar Gate",
    "Sorceress Memorial",
    "Timber",
    "Yaulny Plains",
};
static const int32_t s_rnNodeXY[13][2] = {
    { 24304, -30300 },
    { 12560, -26800 },
    { -14513, -39119 },
    { 30239, -29528 },
    { -32742, -26874 },
    { -39691, -27008 },
    { -36895, -27082 },
    { -38914, -24767 },
    { -16452, -39492 },
    { 88021, 7865 },
    { 81521, 11865 },
    { -22580, -5291 },
    { -31345, -25449 },
};

// edges: nodeA, nodeB, ptOffset, ptCount, lenUnits, simFramesFwd, simFramesRev
static const int ROUTENET_EDGE_COUNT = 14;
static const int32_t s_rnEdges[14][7] = {
    { 6, 7, 0, 23, 3244, 528, 116 },
    { 6, 5, 23, 16, 2876, 49, 48 },
    { 6, 4, 39, 46, 4248, 94, 95 },
    { 4, 12, 85, 23, 2064, 29, 25 },
    { 12, 11, 108, 165, 25298, 1136, 907 },
    { 12, 8, 273, 141, 22564, 827, 805 },
    { 8, 2, 414, 17, 2066, 24, 23 },
    { 7, 5, 431, 26, 2371, 36, 40 },
    { 7, 4, 457, 74, 6892, 177, 176 },
    { 4, 5, 531, 95, 8912, 242, 243 },
    { 0, 1, 626, 146, 12692, 376, 352 },
    { 1, 3, 772, 218, 19522, 777, 895 },
    { 0, 3, 990, 56, 7067, 1075, 315 },
    { 9, 10, 1046, 53, 8154, 247, 246 },
};

// packed polyline points (world coords), 1099 points
static const int ROUTENET_PT_COUNT = 1099;
static const int32_t s_rnPts[1099][2] = {
    {-36864,-27136},{-36932,-27068},{-36992,-26912},{-37060,-26812},{-37188,-26684},{-37248,-26528},
    {-37316,-26428},{-37444,-26300},{-37572,-26172},{-37700,-26044},{-37760,-25888},{-37828,-25788},
    {-37956,-25660},{-38084,-25532},{-38212,-25404},{-38306,-25254},{-38341,-25165},{-38433,-25125},
    {-38522,-25090},{-38596,-25020},{-38724,-24892},{-38852,-24764},{-38912,-24704},{-36864,-27136},
    {-37003,-27008},{-37195,-27008},{-37387,-27008},{-37579,-27008},{-37771,-27008},{-37963,-27008},
    {-38155,-27008},{-38347,-27008},{-38539,-27008},{-38731,-27008},{-38923,-27008},{-39115,-27008},
    {-39307,-27008},{-39499,-27008},{-39691,-27008},{-36895,-27082},{-36799,-27077},{-36703,-27072},
    {-36607,-27068},{-36512,-27062},{-36416,-27058},{-36320,-27053},{-36224,-27048},{-36128,-27044},
    {-36032,-27038},{-35936,-27034},{-35840,-27029},{-35744,-27024},{-35649,-27019},{-35553,-27015},
    {-35457,-27010},{-35361,-27005},{-35265,-27000},{-35169,-26995},{-35073,-26991},{-34977,-26986},
    {-34882,-26981},{-34786,-26976},{-34690,-26971},{-34594,-26967},{-34498,-26962},{-34402,-26957},
    {-34306,-26952},{-34210,-26947},{-34115,-26942},{-34019,-26938},{-33920,-26928},{-33824,-26928},
    {-33741,-26960},{-33652,-26976},{-33556,-26976},{-33480,-27024},{-33405,-27075},{-33328,-27120},
    {-33238,-27104},{-33154,-27074},{-33079,-27024},{-33005,-26973},{-32923,-26939},{-32844,-26896},
    {-32763,-26859},{-32742,-26874},{-32694,-26791},{-32646,-26707},{-32599,-26624},{-32551,-26541},
    {-32504,-26457},{-32456,-26374},{-32408,-26291},{-32361,-26207},{-32313,-26124},{-32251,-26051},
    {-32184,-25984},{-32116,-25916},{-32048,-25848},{-31980,-25780},{-31912,-25712},{-31828,-25667},
    {-31741,-25628},{-31653,-25588},{-31566,-25548},{-31478,-25509},{-31391,-25470},{-31345,-25449},
    {-31345,-25449},{-31473,-25321},{-31575,-25174},{-31684,-25020},{-31768,-24867},{-31828,-24767},
    {-31914,-24618},{-31966,-24515},{-32042,-24362},{-32094,-24259},{-32164,-24103},{-32219,-24002},
    {-32268,-23841},{-32303,-23717},{-32347,-23618},{-32390,-23456},{-32423,-23333},{-32471,-23233},
    {-32512,-23072},{-32518,-22944},{-32538,-22818},{-32562,-22690},{-32577,-22560},{-32609,-22470},
    {-32640,-22304},{-32640,-22176},{-32640,-22048},{-32640,-21920},{-32640,-21792},{-32640,-21664},
    {-32640,-21536},{-32640,-21408},{-32640,-21280},{-32640,-21152},{-32640,-21024},{-32640,-20896},
    {-32640,-20768},{-32640,-20640},{-32640,-20512},{-32640,-20384},{-32640,-20256},{-32640,-20128},
    {-32640,-20000},{-32640,-19872},{-32640,-19744},{-32640,-19616},{-32640,-19488},{-32640,-19360},
    {-32640,-19232},{-32640,-19104},{-32640,-18976},{-32640,-18848},{-32640,-18720},{-32640,-18592},
    {-32640,-18464},{-32640,-18336},{-32640,-18208},{-32640,-18080},{-32640,-17952},{-32640,-17824},
    {-32640,-17696},{-32640,-17568},{-32640,-17440},{-32640,-17312},{-32640,-17184},{-32640,-17056},
    {-32640,-16928},{-32640,-16800},{-32640,-16672},{-32640,-16544},{-32640,-16416},{-32640,-16288},
    {-32640,-16160},{-32640,-16032},{-32640,-15904},{-32640,-15776},{-32572,-15676},{-32444,-15548},
    {-32316,-15420},{-32188,-15292},{-32060,-15164},{-31932,-15036},{-31804,-14908},{-31676,-14780},
    {-31548,-14652},{-31420,-14524},{-31292,-14396},{-31164,-14268},{-31036,-14140},{-30908,-14012},
    {-30780,-13884},{-30652,-13756},{-30524,-13628},{-30396,-13500},{-30268,-13372},{-30140,-13244},
    {-30080,-13088},{-30080,-12960},{-30080,-12832},{-30012,-12732},{-29884,-12604},{-29756,-12476},
    {-29628,-12348},{-29500,-12220},{-29372,-12092},{-29244,-11964},{-29116,-11836},{-28988,-11708},
    {-28860,-11580},{-28732,-11452},{-28604,-11324},{-28476,-11196},{-28348,-11068},{-28220,-10940},
    {-28092,-10812},{-27964,-10684},{-27836,-10556},{-27708,-10428},{-27580,-10300},{-27452,-10172},
    {-27324,-10044},{-27196,-9916},{-27068,-9788},{-26940,-9660},{-26812,-9532},{-26684,-9404},
    {-26556,-9276},{-26428,-9148},{-26300,-9020},{-26172,-8892},{-26044,-8764},{-25916,-8636},
    {-25788,-8508},{-25660,-8380},{-25532,-8252},{-25404,-8124},{-25276,-7996},{-25148,-7868},
    {-25020,-7740},{-24892,-7612},{-24764,-7484},{-24636,-7356},{-24508,-7228},{-24380,-7100},
    {-24252,-6972},{-24124,-6844},{-23996,-6716},{-23868,-6588},{-23740,-6460},{-23595,-6355},
    {-23467,-6227},{-23356,-6076},{-23228,-5948},{-23168,-5792},{-23168,-5664},{-23168,-5536},
    {-23168,-5408},{-23168,-5280},{-23135,-5157},{-23102,-5067},{-22983,-5018},{-22816,-5022},
    {-22640,-5045},{-22548,-5183},{-22528,-5248},{-31345,-25449},{-31217,-25577},{-31083,-25700},
    {-30938,-25812},{-30796,-25925},{-30663,-26047},{-30532,-26172},{-30404,-26300},{-30276,-26428},
    {-30148,-26556},{-30020,-26684},{-29892,-26812},{-29764,-26940},{-29636,-27068},{-29508,-27196},
    {-29380,-27324},{-29252,-27452},{-29124,-27580},{-28996,-27708},{-28868,-27836},{-28740,-27964},
    {-28612,-28092},{-28484,-28220},{-28356,-28348},{-28228,-28476},{-28100,-28604},{-27972,-28732},
    {-27844,-28860},{-27716,-28988},{-27588,-29116},{-27460,-29244},{-27332,-29372},{-27204,-29500},
    {-27076,-29628},{-26948,-29756},{-26820,-29884},{-26692,-30012},{-26564,-30140},{-26436,-30268},
    {-26308,-30396},{-26180,-30524},{-26052,-30652},{-25924,-30780},{-25796,-30908},{-25668,-31036},
    {-25540,-31164},{-25472,-31264},{-25412,-31420},{-25284,-31548},{-25156,-31676},{-25028,-31804},
    {-24900,-31932},{-24772,-32060},{-24681,-32133},{-24587,-32151},{-24431,-32231},{-24303,-32359},
    {-24175,-32487},{-24052,-32621},{-23923,-32761},{-23826,-32914},{-23719,-33061},{-23620,-33212},
    {-23492,-33340},{-23364,-33468},{-23236,-33596},{-23168,-33696},{-23134,-33859},{-23096,-33955},
    {-23063,-34083},{-23040,-34208},{-22983,-34367},{-22855,-34495},{-22724,-34620},{-22596,-34748},
    {-22468,-34876},{-22340,-35004},{-22212,-35132},{-22084,-35260},{-21956,-35388},{-21828,-35516},
    {-21700,-35644},{-21572,-35772},{-21444,-35900},{-21316,-36028},{-21188,-36156},{-21060,-36284},
    {-20932,-36412},{-20804,-36540},{-20676,-36668},{-20548,-36796},{-20420,-36924},{-20292,-37052},
    {-20224,-37152},{-20224,-37280},{-20224,-37408},{-20224,-37536},{-20224,-37664},{-20224,-37792},
    {-20224,-37920},{-20224,-38048},{-20233,-38179},{-20256,-38304},{-20250,-38434},{-20230,-38560},
    {-20224,-38688},{-20224,-38816},{-20224,-38944},{-20224,-39072},{-20164,-39228},{-20088,-39312},
    {-20049,-39400},{-19936,-39484},{-19837,-39488},{-19671,-39512},{-19552,-39552},{-19396,-39612},
    {-19268,-39740},{-19140,-39868},{-19030,-39957},{-18912,-40000},{-18813,-40000},{-18647,-40024},
    {-18528,-40064},{-18426,-40062},{-18337,-40027},{-18187,-39933},{-18078,-39822},{-17992,-39747},
    {-17839,-39663},{-17753,-39588},{-17632,-39552},{-17504,-39552},{-17376,-39552},{-17248,-39552},
    {-17120,-39552},{-16992,-39552},{-16864,-39552},{-16736,-39552},{-16608,-39552},{-16452,-39492},
    {-16452,-39492},{-16352,-39424},{-16224,-39424},{-16096,-39424},{-15968,-39424},{-15840,-39424},
    {-15712,-39424},{-15584,-39424},{-15428,-39364},{-15328,-39296},{-15200,-39296},{-15072,-39296},
    {-14903,-39271},{-14796,-39227},{-14688,-39168},{-14560,-39168},{-14464,-39168},{-38914,-24767},
    {-38945,-24858},{-38977,-24948},{-39008,-25039},{-39040,-25130},{-39071,-25221},{-39102,-25311},
    {-39134,-25402},{-39165,-25493},{-39197,-25583},{-39228,-25674},{-39260,-25765},{-39291,-25856},
    {-39322,-25946},{-39354,-26037},{-39385,-26128},{-39417,-26218},{-39449,-26309},{-39480,-26400},
    {-39511,-26490},{-39543,-26581},{-39574,-26672},{-39605,-26763},{-39637,-26853},{-39668,-26944},
    {-39691,-27008},{-38914,-24767},{-38823,-24798},{-38732,-24829},{-38641,-24860},{-38550,-24890},
    {-38466,-24843},{-38363,-24853},{-38341,-24955},{-38247,-24994},{-38156,-25025},{-38065,-25056},
    {-37974,-25087},{-37883,-25119},{-37792,-25150},{-37702,-25180},{-37611,-25211},{-37520,-25242},
    {-37429,-25273},{-37338,-25304},{-37247,-25335},{-37156,-25366},{-37066,-25398},{-36975,-25429},
    {-36884,-25459},{-36793,-25491},{-36702,-25522},{-36611,-25552},{-36520,-25583},{-36430,-25614},
    {-36339,-25645},{-36248,-25677},{-36157,-25708},{-36066,-25739},{-35975,-25770},{-35885,-25801},
    {-35794,-25832},{-35703,-25862},{-35612,-25893},{-35521,-25924},{-35430,-25955},{-35340,-25987},
    {-35249,-26018},{-35158,-26049},{-35067,-26080},{-34976,-26112},{-34880,-26112},{-34797,-26144},
    {-34708,-26160},{-34612,-26160},{-34516,-26160},{-34447,-26225},{-34379,-26293},{-34311,-26361},
    {-34243,-26429},{-34175,-26497},{-34107,-26565},{-34040,-26632},{-33972,-26700},{-33899,-26757},
    {-33822,-26802},{-33749,-26859},{-33672,-26904},{-33595,-26949},{-33518,-26994},{-33445,-27051},
    {-33368,-27096},{-33282,-27120},{-33194,-27098},{-33117,-27053},{-33035,-27019},{-32957,-26976},
    {-32874,-26944},{-32794,-26906},{-32736,-26880},{-32736,-26880},{-32823,-26920},{-32911,-26958},
    {-32998,-26999},{-33085,-27040},{-33170,-27084},{-33260,-27114},{-33352,-27100},{-33437,-27056},
    {-33513,-26998},{-33596,-26949},{-33679,-26900},{-33760,-26850},{-33837,-26793},{-33918,-26742},
    {-33992,-26680},{-34060,-26612},{-34128,-26544},{-34196,-26476},{-34263,-26409},{-34331,-26341},
    {-34399,-26273},{-34468,-26206},{-34546,-26160},{-34642,-26160},{-34737,-26155},{-34830,-26131},
    {-34922,-26112},{-35016,-26098},{-35107,-26067},{-35197,-26036},{-35288,-26005},{-35379,-25973},
    {-35470,-25942},{-35560,-25911},{-35651,-25880},{-35742,-25849},{-35833,-25819},{-35924,-25788},
    {-36015,-25756},{-36106,-25725},{-36197,-25694},{-36287,-25663},{-36378,-25632},{-36469,-25601},
    {-36560,-25569},{-36651,-25539},{-36742,-25508},{-36833,-25477},{-36923,-25446},{-37014,-25416},
    {-37105,-25384},{-37196,-25352},{-37287,-25321},{-37378,-25291},{-37468,-25260},{-37559,-25229},
    {-37650,-25198},{-37741,-25167},{-37832,-25136},{-37923,-25105},{-38014,-25074},{-38104,-25043},
    {-38197,-25025},{-38293,-25027},{-38389,-25044},{-38485,-25030},{-38581,-25032},{-38677,-25033},
    {-38773,-25035},{-38869,-25036},{-38965,-25038},{-39026,-25089},{-39057,-25180},{-39088,-25271},
    {-39120,-25362},{-39151,-25452},{-39183,-25543},{-39214,-25634},{-39246,-25724},{-39277,-25815},
    {-39308,-25906},{-39340,-25997},{-39371,-26087},{-39403,-26178},{-39435,-26268},{-39466,-26359},
    {-39497,-26450},{-39529,-26541},{-39560,-26631},{-39591,-26722},{-39623,-26813},{-39654,-26904},
    {-39686,-26994},{-39691,-27008},{23936,-29952},{23904,-29928},{23872,-29928},{23840,-29952},
    {23744,-29952},{23648,-29952},{23552,-29952},{23456,-29952},{23360,-29952},{23264,-29952},
    {23168,-29952},{23100,-29884},{23032,-29816},{22964,-29748},{22890,-29696},{22794,-29696},
    {22698,-29696},{22602,-29696},{22506,-29696},{22410,-29696},{22314,-29696},{22218,-29696},
    {22122,-29696},{22026,-29696},{21955,-29635},{21887,-29568},{21791,-29568},{21695,-29568},
    {21599,-29568},{21503,-29568},{21407,-29568},{21311,-29568},{21215,-29568},{21119,-29567},
    {21051,-29499},{20980,-29440},{20884,-29440},{20788,-29440},{20692,-29440},{20596,-29440},
    {20500,-29440},{20404,-29440},{20321,-29409},{20253,-29341},{20185,-29273},{20117,-29205},
    {20049,-29137},{19982,-29070},{19914,-29002},{19846,-28934},{19778,-28866},{19710,-28798},
    {19642,-28730},{19574,-28662},{19506,-28594},{19438,-28526},{19371,-28459},{19292,-28416},
    {19196,-28416},{19100,-28416},{19004,-28416},{18908,-28416},{18812,-28416},{18716,-28416},
    {18620,-28416},{18524,-28416},{18428,-28416},{18332,-28416},{18236,-28416},{18140,-28416},
    {18044,-28416},{17948,-28416},{17852,-28416},{17756,-28416},{17660,-28416},{17564,-28416},
    {17468,-28416},{17372,-28416},{17276,-28416},{17180,-28416},{17084,-28416},{16999,-28391},
    {16931,-28323},{16863,-28255},{16795,-28187},{16727,-28119},{16659,-28051},{16591,-27983},
    {16524,-27916},{16456,-27848},{16388,-27780},{16320,-27712},{16252,-27644},{16184,-27576},
    {16116,-27508},{16048,-27440},{15980,-27372},{15913,-27305},{15845,-27237},{15777,-27169},
    {15694,-27136},{15598,-27136},{15502,-27136},{15406,-27136},{15310,-27136},{15214,-27136},
    {15118,-27136},{15022,-27136},{14926,-27136},{14830,-27136},{14734,-27136},{14638,-27136},
    {14542,-27136},{14452,-27124},{14384,-27056},{14307,-27008},{14211,-27008},{14115,-27008},
    {14019,-27008},{13923,-27008},{13827,-27008},{13731,-27008},{13635,-27008},{13539,-27008},
    {13443,-27008},{13347,-27008},{13269,-26965},{13201,-26897},{13133,-26829},{13066,-26762},
    {13038,-26754},{13006,-26757},{12976,-26784},{12944,-26787},{12912,-26790},{12878,-26769},
    {12846,-26772},{12815,-26775},{12783,-26778},{12751,-26782},{12719,-26785},{12687,-26788},
    {12655,-26791},{12621,-26770},{12589,-26773},{12560,-26800},{12544,-26752},{12514,-26763},
    {12484,-26775},{12446,-26764},{12416,-26775},{12386,-26787},{12356,-26798},{12350,-26847},
    {12316,-26868},{12327,-26907},{12315,-26937},{12304,-26967},{12292,-26997},{12288,-27028},
    {12288,-27060},{12287,-27092},{12287,-27124},{12287,-27156},{12287,-27188},{12286,-27220},
    {12286,-27252},{12368,-27265},{12464,-27265},{12555,-27275},{12623,-27343},{12698,-27389},
    {12795,-27385},{12886,-27411},{12985,-27392},{13081,-27392},{13177,-27392},{13273,-27392},
    {13369,-27392},{13465,-27392},{13561,-27392},{13657,-27392},{13753,-27392},{13849,-27392},
    {13945,-27392},{14041,-27392},{14137,-27392},{14233,-27392},{14329,-27392},{14425,-27392},
    {14521,-27392},{14609,-27409},{14677,-27477},{14756,-27520},{14852,-27520},{14948,-27520},
    {15044,-27520},{15140,-27520},{15236,-27520},{15332,-27520},{15428,-27520},{15524,-27520},
    {15620,-27520},{15716,-27520},{15812,-27520},{15897,-27545},{15965,-27613},{16033,-27681},
    {16101,-27749},{16169,-27817},{16237,-27885},{16304,-27952},{16372,-28020},{16440,-28088},
    {16508,-28156},{16603,-28160},{16699,-28160},{16795,-28160},{16891,-28160},{16987,-28160},
    {17083,-28160},{17179,-28160},{17275,-28160},{17371,-28160},{17467,-28160},{17563,-28160},
    {17659,-28160},{17755,-28160},{17851,-28160},{17947,-28160},{18043,-28160},{18139,-28160},
    {18235,-28160},{18331,-28160},{18427,-28160},{18523,-28160},{18619,-28160},{18715,-28160},
    {18811,-28160},{18907,-28160},{19003,-28160},{19099,-28160},{19195,-28160},{19291,-28160},
    {19387,-28160},{19483,-28160},{19579,-28160},{19675,-28160},{19771,-28160},{19867,-28160},
    {19963,-28160},{20059,-28160},{20155,-28160},{20251,-28160},{20347,-28160},{20443,-28160},
    {20539,-28160},{20635,-28160},{20731,-28160},{20827,-28160},{20923,-28160},{21019,-28160},
    {21115,-28160},{21211,-28160},{21307,-28160},{21403,-28160},{21499,-28160},{21595,-28160},
    {21691,-28160},{21787,-28160},{21883,-28160},{21979,-28160},{22075,-28160},{22171,-28160},
    {22267,-28160},{22363,-28160},{22459,-28160},{22555,-28160},{22651,-28160},{22747,-28160},
    {22843,-28160},{22939,-28160},{23035,-28160},{23131,-28160},{23227,-28160},{23323,-28160},
    {23419,-28160},{23515,-28160},{23611,-28160},{23707,-28160},{23803,-28160},{23899,-28160},
    {23995,-28160},{24091,-28160},{24187,-28160},{24283,-28160},{24379,-28160},{24475,-28160},
    {24571,-28160},{24667,-28160},{24763,-28160},{24859,-28160},{24955,-28160},{25051,-28160},
    {25147,-28160},{25243,-28160},{25339,-28160},{25435,-28160},{25531,-28160},{25627,-28160},
    {25723,-28160},{25819,-28160},{25915,-28160},{26011,-28160},{26107,-28160},{26203,-28160},
    {26299,-28160},{26395,-28160},{26491,-28160},{26587,-28160},{26683,-28160},{26779,-28160},
    {26875,-28160},{26971,-28160},{27067,-28160},{27163,-28160},{27259,-28160},{27355,-28160},
    {27451,-28160},{27547,-28160},{27643,-28160},{27712,-28224},{27780,-28292},{27848,-28360},
    {27921,-28416},{28017,-28416},{28113,-28416},{28209,-28416},{28305,-28416},{28401,-28416},
    {28497,-28416},{28593,-28416},{28689,-28416},{28785,-28416},{28881,-28416},{28977,-28416},
    {29068,-28428},{29136,-28496},{29203,-28563},{29271,-28631},{29339,-28699},{29407,-28767},
    {29475,-28835},{29543,-28903},{29611,-28971},{29679,-29039},{29746,-29106},{29814,-29174},
    {29882,-29242},{29950,-29310},{30018,-29378},{30086,-29446},{30154,-29514},{30208,-29568},
    {23936,-29952},{23930,-29912},{23945,-29884},{23967,-29860},{23975,-29828},{23990,-29800},
    {24020,-29779},{24131,-29755},{24288,-29760},{24416,-29760},{24544,-29760},{24672,-29760},
    {24800,-29767},{24890,-29727},{25056,-29696},{25184,-29696},{25312,-29696},{25440,-29696},
    {25568,-29696},{25696,-29696},{25824,-29696},{25924,-29628},{26080,-29568},{26208,-29568},
    {26336,-29568},{26464,-29568},{26564,-29500},{26692,-29372},{26820,-29380},{26976,-29440},
    {27104,-29440},{27232,-29440},{27360,-29440},{27488,-29440},{27616,-29440},{27744,-29440},
    {27872,-29440},{28000,-29440},{28100,-29372},{28228,-29244},{28356,-29116},{28484,-28988},
    {28612,-28860},{28768,-28800},{28896,-28800},{28996,-28868},{29124,-28996},{29252,-29124},
    {29380,-29252},{29508,-29380},{29636,-29508},{29792,-29568},{29920,-29568},{30048,-29568},
    {30176,-29568},{30208,-29568},{88064,7808},{87968,7808},{87840,7808},{87712,7808},
    {87584,7808},{87456,7808},{87328,7808},{87228,7876},{87100,8004},{86944,8064},
    {86816,8064},{86688,8064},{86560,8064},{86432,8064},{86304,8064},{86204,8132},
    {86076,8260},{85948,8388},{85820,8516},{85692,8644},{85564,8772},{85436,8900},
    {85280,8960},{85152,8960},{85024,8960},{84896,8960},{84768,8960},{84640,8960},
    {84540,9028},{84412,9156},{84284,9284},{84156,9412},{84028,9540},{83900,9668},
    {83772,9796},{83644,9924},{83516,10052},{83388,10180},{83260,10308},{83132,10436},
    {83004,10564},{82876,10692},{82748,10820},{82620,10948},{82492,11076},{82364,11204},
    {82236,11332},{82108,11460},{81980,11588},{81824,11648},{81724,11716},{81596,11844},
    {81536,11904},
};
// ============================ RUNTIME (handwritten) =========================
// v0.18.3.209 (#70): PRECOMPUTED VALIDATED ROUTE NETWORK planner. The .207/.208
// BATs proved the structural failure of grid routing at the Galbadia pass: the
// corridor's only reliable line (z=-25086+-8 through x in [-44700,-44540]) lies
// BETWEEN 128u grid rows, so no grid plan can express it and the executor
// ground against the sticky north lane every time. These edges are exact
// polylines refined offline onto the MAXIMUM-CLEARANCE channel of each
// corridor and validated by the fitted stateful engine replica + full executor
// simulation in both directions (offline/gen_routenet.py, offline/ROUTENET.md).
// The planner tries the network FIRST: short local hop onto the nearest edge
// vertex, node-graph Dijkstra to the vertex nearest the target, short local
// hop off. Grid A* remains the fallback for off-network legs and is untouched.
//
// v0.18.3.210 (#71): LOCATION NODES ARE NEVER TRANSITED. The .209 BAT drove
// through the Galbadia Garden / Galbadia Station nodes as Dijkstra
// intermediates (their coords are entry aims INSIDE their firing areas) and
// re-fired those fields mid-route (OFF-TARGET pauses 10:23:24 / 10:24:03 /
// 10:24:29). Fix: hard transit rule (junctions + at-mouth seeded starts +
// the target node only), a validated junction<->junction bypass edge
// GG East Plains <-> GG West Plains so Station/Timber/Dollet chains do not
// need GG or Station as intermediates, and a foreign-firing-area sweep on
// the straight local-hop branch (parity with the hop A* branch).
//
// v0.18.3.211 (#72): PASS REMOVED, EAST REROUTE (data-only change). The .210
// BAT proved the Galbadia pass impassable live: 26-29 km of cycling on the
// validated max-clearance z=-25088 line, zero crossings (the 6-8u modeled
// margin was real; the corrected replica predicted the fail). The pass edge
// and the .205 gap edge (GG East Plains<->Dollet, deterministic sim block at
// the massif-tip skirt seam) are gone from the tables; the fully validated
// .209 Dollet<->Timber corridor is split at two new junctions -- Yaulny
// Plains (-31345,-25449) at the only belt crossing both the replica and the
// executor sim accept, and Hasberry Plains (-16452,-39492) at the Dollet
// mouth OUTSIDE Dollet's firing bbox (Dollet stays destination-only under
// the .210 hard transit rule) -- plus a new 2.1km GG East Plains<->Yaulny
// Plains link. Full 20/20 matrix arrives; Timber traffic is a LONGER but
// steady drive east. Runtime code below is UNCHANGED.
//
// Included from world_map.cpp AFTER world_map_planner.inl (uses
// FootBlockedCached / FootBlocked8 / IsNavBlockedWorld / TorusBearing /
// CalculateWrappedDistance / s_entryAims / drive-path state); PlanDrivePath
// calls RouteNetPlan via a forward declaration.

// Junction nodes carry " Plains" in their name (generator convention): they
// sit in open terrain OUTSIDE every decoded firing area. Every other node is
// a LOCATION node -- its coordinate is an entry AIM POINT *inside* that
// location's decoded firing area, so driving THROUGH it fires the field
// entry. v0.18.3.210: the .209 BAT proved the 8000u soft penalty merely
// re-ranked such routes (Dijkstra still chained through Galbadia Garden and
// Galbadia Station; ggview1/station fields fired mid-route three times) --
// location transit is now FORBIDDEN outright, see RouteNetPlan.
static bool RnIsJunction(int n)
{
    return strstr(s_rnNodeNames[n], " Plains") != NULL;
}

// Does node n coincide with the current drive target (its own entry aim)?
// Ending a chain at the target's node is the point of the drive; ending at
// any other location node would transit that location's firing area.
static bool RnIsTargetNode(int n, int32_t tx, int32_t ty)
{
    return CalculateWrappedDistance(s_rnNodeXY[n][0], s_rnNodeXY[n][1], tx, ty) <= 700.0;
}

// A seeded e1 endpoint that is a location node may start the chain only if
// the walk-back from the start position is at most this long -- i.e. the
// player is standing at that location's mouth (just exited its field), so
// its firing area is the start's own context, not a foreign one.
static const double RN_START_MOUTH_MAX = 900.0;

// Cumulative arc length from edge start to each vertex, computed once.
static double* s_rnArc = NULL;            // ROUTENET_PT_COUNT entries
static void RnEnsureArc()
{
    if (s_rnArc) return;
    static std::vector<double> arc;
    arc.assign(ROUTENET_PT_COUNT, 0.0);
    for (int e = 0; e < ROUTENET_EDGE_COUNT; e++) {
        const int off = (int)s_rnEdges[e][2], cnt = (int)s_rnEdges[e][3];
        double acc = 0.0;
        arc[off] = 0.0;
        for (int i = 1; i < cnt; i++) {
            acc += CalculateWrappedDistance(s_rnPts[off + i - 1][0], s_rnPts[off + i - 1][1],
                                            s_rnPts[off + i][0],     s_rnPts[off + i][1]);
            arc[off + i] = acc;
        }
    }
    s_rnArc = arc.data();
}

// Nearest polyline vertex on any edge (torus metric). Returns edge, vertex
// index (edge-local) and distance.
static bool RnNearestVertex(int32_t x, int32_t y, int* outE, int* outI, double* outD)
{
    int be = -1, bi = 0; double bd = 1e30;
    for (int e = 0; e < ROUTENET_EDGE_COUNT; e++) {
        const int off = (int)s_rnEdges[e][2], cnt = (int)s_rnEdges[e][3];
        for (int i = 0; i < cnt; i++) {
            double d = CalculateWrappedDistance(x, y, s_rnPts[off + i][0], s_rnPts[off + i][1]);
            if (d < bd) { bd = d; be = e; bi = i; }
        }
    }
    *outE = be; *outI = bi; *outD = bd;
    return be >= 0;
}

// 8u swept walkability of a straight segment (both endpoints assumed near
// ground). Used for the trivial local-hop case.
static bool RnSegBlocked(int32_t ax, int32_t ay, int32_t bx, int32_t by)
{
    double dx = (double)(bx - ax), dy = (double)(by - ay);
    double len = sqrt(dx * dx + dy * dy);
    if (len < 1.0) return false;
    int n = (int)(len / 8.0) + 1;
    for (int i = 1; i <= n; i++) {
        int32_t px = ax + (int32_t)(dx * i / n), py = ay + (int32_t)(dy * i / n);
        if (FootBlocked8(px, py) || IsNavBlockedWorld(px, py)) return true;
    }
    return false;
}

// Is (x,y) inside a decoded firing area that does NOT contain either hop
// endpoint? (A hop may enter the area its own start or target sits in --
// e.g. the final hop to an entry aim -- but must not clip a foreign one.)
static bool RnInForeignArea(int32_t x, int32_t y,
                            int32_t ex0, int32_t ey0, int32_t ex1, int32_t ey1)
{
    for (int i = 0; i < ENTRY_AIM_COUNT; i++) {
        const EntryAimInfo& a = s_entryAims[i];
        if (x < a.x0 - 64 || x > a.x1 + 64 || y < a.y0 - 64 || y > a.y1 + 64) continue;
        // endpoint exemption
        if (ex0 >= a.x0 - 64 && ex0 <= a.x1 + 64 && ey0 >= a.y0 - 64 && ey0 <= a.y1 + 64) continue;
        if (ex1 >= a.x0 - 64 && ex1 <= a.x1 + 64 && ey1 >= a.y0 - 64 && ey1 <= a.y1 + 64) continue;
        return true;
    }
    return false;
}

// v0.18.3.210: 64u-sampled foreign-firing-area sweep of a straight hop
// segment. The bounded A* branch below already refuses foreign-area cells,
// but the straight branch used to trust walkability alone -- a hop clipping
// a non-endpoint firing area must instead fall through to the A* (which
// routes around it or fails -> plan declined -> grid fallback owns it).
static bool RnSegClipsForeignArea(int32_t ax, int32_t ay, int32_t bx, int32_t by)
{
    double dx = (double)(bx - ax), dy = (double)(by - ay);
    double len = sqrt(dx * dx + dy * dy);
    int n = (int)(len / 64.0) + 1;
    for (int i = 0; i <= n; i++) {
        int32_t px = ax + (int32_t)(dx * i / n), py = ay + (int32_t)(dy * i / n);
        if (RnInForeignArea(px, py, ax, ay, bx, by)) return true;
    }
    return false;
}

// LOCAL HOP: straight segment if swept-clear, else a small bounded 128u A*
// (FootBlockedCached walkability, |dH|<200 step gate, learned-block and
// foreign-firing-area avoidance). Appends waypoints EXCLUDING (fx,fy),
// INCLUDING (tx,ty). Returns count appended, or -1 on failure.
static int RnLocalHop(int32_t fx, int32_t fy, int32_t tx, int32_t ty,
                      int32_t* outX, int32_t* outY, int maxOut)
{
    double dist = CalculateWrappedDistance(fx, fy, tx, ty);
    if (dist < 16.0) return 0;
    if (dist <= 2048.0 && !RnSegBlocked(fx, fy, tx, ty)
            && !RnSegClipsForeignArea(fx, fy, tx, ty)) {
        int n = (int)(dist / 128.0) + 1;
        if (n > maxOut) return -1;
        for (int i = 1; i <= n; i++) {
            outX[i - 1] = fx + (int32_t)((double)(tx - fx) * i / n);
            outY[i - 1] = fy + (int32_t)((double)(ty - fy) * i / n);
        }
        return n;
    }
    // bounded A* on 128u cells, bbox = endpoints + 8 cells
    const int STEP = 128;
    int cx0 = (int)floor((double)((fx < tx) ? fx : tx) / STEP) - 8;
    int cy0 = (int)floor((double)((fy < ty) ? fy : ty) / STEP) - 8;
    int cx1 = (int)ceil((double)((fx > tx) ? fx : tx) / STEP) + 8;
    int cy1 = (int)ceil((double)((fy > ty) ? fy : ty) / STEP) + 8;
    const int W = cx1 - cx0 + 1, H = cy1 - cy0 + 1;
    if (W <= 0 || H <= 0 || W * H > 4096) return -1;
    std::vector<int>   g(W * H, 0x3FFFFFFF);
    std::vector<int>   came(W * H, -1);
    std::vector<int8_t> hcache(W * H, -1);   // ground-height known? (bool via -1/0/1 walkable)
    const int sx = (int)floor((double)fx / STEP) - cx0, sy = (int)floor((double)fy / STEP) - cy0;
    const int gx = (int)floor((double)tx / STEP) - cx0, gy = (int)floor((double)ty / STEP) - cy0;
    if (sx < 0 || sy < 0 || gx < 0 || gy < 0 || sx >= W || sy >= H || gx >= W || gy >= H) return -1;
    // linear Dijkstra (W*H <= 4096 cells): pop = full scan for the unvisited
    // minimum -- bounded ~16M int compares worst case, a one-time cost per plan.
    std::vector<uint8_t> vis(W * H, 0);
    const int sLi = sy * W + sx, gLi = gy * W + gx;
    g[sLi] = 0;
    bool found = false;
    for (;;) {
        int li = -1, bg = 0x3FFFFFFF;
        for (int i = 0; i < W * H; i++)
            if (!vis[i] && g[i] < bg) { bg = g[i]; li = i; }
        if (li < 0) break;
        vis[li] = 1;
        if (li == gLi) { found = true; break; }
        const int ccx = li % W + cx0, ccy = li / W + cy0;
        const int32_t wx = ccx * STEP + STEP / 2, wy = ccy * STEP + STEP / 2;
        int wh = WorldGroundHeightLocal(wx, wy);
        for (int k = 0; k < 8; k++) {
            static const int NB[8][2] = { {1,0},{-1,0},{0,1},{0,-1},{1,1},{1,-1},{-1,1},{-1,-1} };
            const int nx = ccx + NB[k][0], ny = ccy + NB[k][1];
            if (nx < cx0 || ny < cy0 || nx > cx1 || ny > cy1) continue;
            const int nLi = (ny - cy0) * W + (nx - cx0);
            if (vis[nLi]) continue;
            const int32_t nwx = nx * STEP + STEP / 2, nwy = ny * STEP + STEP / 2;
            if (hcache[nLi] < 0)
                hcache[nLi] = (FootBlockedCached(nwx, nwy) || IsNavBlockedWorld(nwx, nwy)
                               || RnInForeignArea(nwx, nwy, fx, fy, tx, ty)) ? 0 : 1;
            if (!hcache[nLi]) continue;
            int nh = WorldGroundHeightLocal(nwx, nwy);
            if (wh != WGH_NO_GROUND && nh != WGH_NO_GROUND && abs(nh - wh) >= 200) continue;
            const int cost = (NB[k][0] && NB[k][1]) ? 181 : 128;
            const int ng = g[li] + cost;
            if (ng < g[nLi]) { g[nLi] = ng; came[nLi] = li; }
        }
    }
    if (!found) return -1;
    int rev[128]; int rc = 0; int cur = gLi;
    while (cur != -1 && rc < 128) { rev[rc++] = cur; if (cur == sLi) break; cur = came[cur]; }
    if (rc == 0 || rev[rc - 1] != sLi) return -1;
    int n = 0;
    for (int i = rc - 2; i >= 0 && n < maxOut - 1; i--) {   // skip the start cell
        outX[n] = (rev[i] % W + cx0) * STEP + STEP / 2;
        outY[n] = (rev[i] / W + cy0) * STEP + STEP / 2;
        n++;
    }
    if (n >= maxOut) return -1;
    outX[n] = tx; outY[n] = ty; n++;                        // exact hop target last
    return n;
}

// Append one edge-vertex waypoint to the drive path (world + packed fine cell).
static bool RnEmit(int32_t wx, int32_t wy, int& n)
{
    if (n >= DRIVE_PATH_MAX) return false;
    s_drivePathWX[n] = wx; s_drivePathWY[n] = wy;
    int fc = WorldXToFineCol(wx), fr = WorldYToFineRow(wy);
    if (fr < 0) fr = 0; else if (fr >= WM_FINE_ROWS) fr = WM_FINE_ROWS - 1;
    if (fc < 0) fc = 0; else if (fc >= WM_FINE_COLS) fc = WM_FINE_COLS - 1;
    s_drivePath[n] = PackSeg(fr, fc);
    n++;
    return true;
}

// Per-drive attempt limiter: a drive that keeps replanning ONTO the network
// and grinding anyway must eventually fall through to the grid planner
// (learned blocks make the grid detour differ; the network answer would not).
static DWORD s_rnPlanDriveId = 0;
static int   s_rnPlansThisDrive = 0;

static bool RouteNetPlan(int32_t startX, int32_t startY)
{
    if (ROUTENET_EDGE_COUNT <= 0) return false;
    // v0.18.3.219: cap identity includes s_driveWatchdogGen (bumped on every
    // battle/field pause-resume, cf. .216). Observed live 22:43-23:03: on the
    // 35 km Dollet->Timber leg with an encounter every ~600 u, the first 3
    // battle resumes exhausted the 4-plan budget; every later resume fell to
    // the grid planner mid-corridor and the drive wandered (dist to Timber
    // ROSE across resumes, WPSKIP churn). Battle resumes are normal drive
    // continuations, not replan-grind: each one now refreshes the budget,
    // while the cap still bounds replan loops within continuous driving.
    DWORD rnKey = s_driveStartTime + s_driveWatchdogGen;
    if (s_rnPlanDriveId != rnKey) {
        s_rnPlanDriveId = rnKey;
        s_rnPlansThisDrive = 0;
    }
    if (s_rnPlansThisDrive >= 4) {
        Log::World("WorldMap: [ROUTENET] declined: 4 network plans already this drive -> grid fallback");
        return false;
    }
    RnEnsureArc();
    const int32_t tx = s_driveTargetX, ty = s_driveTargetY;
    int e1, i1, e2, i2; double d1, d2;
    if (!RnNearestVertex(startX, startY, &e1, &i1, &d1)) return false;
    if (!RnNearestVertex(tx, ty, &e2, &i2, &d2)) return false;
    if (d1 > 2048.0 || d2 > 2048.0) {
        Log::World("WorldMap: [ROUTENET] declined: off-network (start %.0fu, target %.0fu from nearest edge)", d1, d2);
        return false;
    }
    const int off1 = (int)s_rnEdges[e1][2], cnt1 = (int)s_rnEdges[e1][3];
    const int off2 = (int)s_rnEdges[e2][2], cnt2 = (int)s_rnEdges[e2][3];

    // ---- assemble the vertex index chain (edge, from, to) ------------------
    struct Leg { int e; int a; int b; };            // walk edge e vertex a -> b
    Leg legs[24]; int nLegs = 0;
    if (e1 == e2) {
        Leg L = { e1, i1, i2 }; legs[nLegs++] = L;
    } else {
        // Dijkstra over the node graph seeded from e1's two endpoints.
        double dist[ROUTENET_NODE_COUNT];
        int    prevE[ROUTENET_NODE_COUNT];          // edge used to reach node
        int    prevN[ROUTENET_NODE_COUNT];          // previous node (-1 = virtual start)
        bool   done[ROUTENET_NODE_COUNT];
        for (int i = 0; i < ROUTENET_NODE_COUNT; i++) { dist[i] = 1e30; prevE[i] = -1; prevN[i] = -2; done[i] = false; }
        const int a1 = (int)s_rnEdges[e1][0], b1 = (int)s_rnEdges[e1][1];
        dist[a1] = s_rnArc[off1 + i1];                                   // walk back to edge start
        prevE[a1] = e1; prevN[a1] = -1;
        const double toB = s_rnArc[off1 + cnt1 - 1] - s_rnArc[off1 + i1];
        if (toB < dist[b1]) { dist[b1] = toB; prevE[b1] = e1; prevN[b1] = -1; }
        for (;;) {
            int u = -1; double bu = 1e30;
            for (int i = 0; i < ROUTENET_NODE_COUNT; i++)
                if (!done[i] && dist[i] < bu) { bu = dist[i]; u = i; }
            if (u < 0) break;
            done[u] = true;
            // v0.18.3.210 HARD TRANSIT RULE: relax edges OUT of u only if u
            // is a junction, or a seeded e1 endpoint the start is standing at
            // (walk-back <= RN_START_MOUTH_MAX). Any other location node is
            // terminal: reachable as a destination, never driven through.
            if (!(RnIsJunction(u) || (prevN[u] == -1 && dist[u] <= RN_START_MOUTH_MAX)))
                continue;
            for (int e = 0; e < ROUTENET_EDGE_COUNT; e++) {
                const int ea = (int)s_rnEdges[e][0], eb = (int)s_rnEdges[e][1];
                const double len = (double)s_rnEdges[e][4];
                if (ea == u && dist[u] + len < dist[eb]) { dist[eb] = dist[u] + len; prevE[eb] = e; prevN[eb] = u; }
                if (eb == u && dist[u] + len < dist[ea]) { dist[ea] = dist[u] + len; prevE[ea] = e; prevN[ea] = u; }
            }
        }
        // best entry node of e2 (add the partial walk to i2). The e2 partial
        // leg walks OUT of the entry node, i.e. transits it -- so a location
        // node is an eligible entry only if it IS the drive target (its area
        // is the destination) or a seeded mouth the start is standing at.
        const int a2 = (int)s_rnEdges[e2][0], b2 = (int)s_rnEdges[e2][1];
        double ca = dist[a2] + s_rnArc[off2 + i2];
        double cb = dist[b2] + (s_rnArc[off2 + cnt2 - 1] - s_rnArc[off2 + i2]);
        const bool okA = dist[a2] < 1e29 && (RnIsJunction(a2) || RnIsTargetNode(a2, tx, ty)
                          || (prevN[a2] == -1 && dist[a2] <= RN_START_MOUTH_MAX));
        const bool okB = dist[b2] < 1e29 && (RnIsJunction(b2) || RnIsTargetNode(b2, tx, ty)
                          || (prevN[b2] == -1 && dist[b2] <= RN_START_MOUTH_MAX));
        if (!okA && !okB) {
            Log::World("WorldMap: [ROUTENET] declined: no transit-legal network path between edges %d and %d", e1, e2);
            return false;
        }
        int entry = (!okB || (okA && ca <= cb)) ? a2 : b2;
        // reconstruct node chain back to the virtual start
        int chain[16]; int nc = 0; int u = entry;
        while (u != -1 && nc < 16) { chain[nc++] = u; if (prevN[u] == -1) break; u = prevN[u]; }
        if (nc == 0 || prevN[chain[nc - 1]] != -1) return false;
        // legs: e1 partial (i1 -> chain[nc-1] end), then full edges, then e2 partial
        const int firstNode = chain[nc - 1];
        {
            Leg L = { e1, i1, (firstNode == a1) ? 0 : cnt1 - 1 }; legs[nLegs++] = L;
        }
        for (int i = nc - 1; i > 0; i--) {
            const int from = chain[i], to = chain[i - 1];
            const int e = prevE[to];
            const int ea = (int)s_rnEdges[e][0];
            const int ecnt = (int)s_rnEdges[e][3];
            Leg L = { e, (from == ea) ? 0 : ecnt - 1, (from == ea) ? ecnt - 1 : 0 };
            if (nLegs >= 24) return false;
            legs[nLegs++] = L;
        }
        {
            Leg L = { e2, (entry == a2) ? 0 : cnt2 - 1, i2 };
            if (nLegs >= 24) return false;
            legs[nLegs++] = L;
        }
    }

    // ---- local hops + splice into the drive-path arrays --------------------
    int32_t hopX[64], hopY[64];
    const int32_t nx0 = s_rnPts[off1 + i1][0], ny0 = s_rnPts[off1 + i1][1];
    int hn = RnLocalHop(startX, startY, nx0, ny0, hopX, hopY, 48);
    if (hn < 0) {
        Log::World("WorldMap: [ROUTENET] declined: no local hop onto the network (%.0fu)", d1);
        return false;
    }
    int n = 0;
    bool ok = true;
    for (int i = 0; i < hn && ok; i++) ok = RnEmit(hopX[i], hopY[i], n);
    for (int L = 0; L < nLegs && ok; L++) {
        const int off = (int)s_rnEdges[legs[L].e][2];
        const int stepDir = (legs[L].b >= legs[L].a) ? 1 : -1;
        for (int i = legs[L].a; ok; i += stepDir) {
            if (!(n > 0 && s_drivePathWX[n - 1] == s_rnPts[off + i][0]
                       && s_drivePathWY[n - 1] == s_rnPts[off + i][1]))
                ok = RnEmit(s_rnPts[off + i][0], s_rnPts[off + i][1], n);
            if (i == legs[L].b) break;
        }
    }
    if (ok && n > 0) {
        const int32_t exX = s_drivePathWX[n - 1], exY = s_drivePathWY[n - 1];
        int hn2 = RnLocalHop(exX, exY, tx, ty, hopX, hopY, 48);
        if (hn2 < 0) {
            Log::World("WorldMap: [ROUTENET] declined: no local hop off the network (%.0fu)", d2);
            return false;
        }
        for (int i = 0; i < hn2 && ok; i++) ok = RnEmit(hopX[i], hopY[i], n);
    }
    if (!ok || n < 2) {
        Log::World("WorldMap: [ROUTENET] declined: spliced path too long/short (%d pts)", n);
        return false;
    }
    s_drivePathLen = n; s_drivePathIdx = 0;
    s_drivePathPlanned = true; s_drivePathWorld = true;
    s_drivePlanExpanded = 0; s_drivePlanDist = 0; s_driveNavmeshPath = false;
    s_rnPlansThisDrive++;
    {
        char via[192]; int vp = 0; via[0] = 0;
        for (int L = 0; L < nLegs && vp < (int)sizeof(via) - 40; L++) {
            const int e = legs[L].e;
            vp += snprintf(via + vp, sizeof(via) - vp, "%s%s<->%s", L ? " " : "",
                           s_rnNodeNames[s_rnEdges[e][0]], s_rnNodeNames[s_rnEdges[e][1]]);
        }
        Log::World("WorldMap: [ROUTENET] plan ok: hopOn=%d pts (%.0fu), %d leg(s) via %s, hopOff (%.0fu), total %d pts (plan %d/4 this drive)",
                   hn, d1, nLegs, via, d2, n, s_rnPlansThisDrive);
    }
    return true;
}
